### ISSUE TITLE
terraform_docs args throws unrecognized option error

### ISSUE THREAD

**Issue by sleterrier** [antonbabenko/pre-commit-terraform#102]
```
- repo: git://github.com/antonbabenko/pre-commit-terraform
  rev: v1.29.0
  hooks:
    - id: terraform_validate
    - id: terraform_fmt
    - id: terraform_docs
      args: ['--sort-by-required', '--no-providers']
```

is currently failing with the following error:
```
Terraform docs...........................................................Failed
- hook id: terraform_docs
- exit code: 1

getopt: unrecognized option '--sort-by-required'
getopt: unrecognized option '--no-providers'
```
```
# terraform-docs -v
terraform-docs version v0.0.0- v0.9.1 darwin/amd64
```

After a few failed attempts at digging in the scripts to figure out a fix, I am resorting to asking for competent help here.. :)

**Comment by rquadling** [comment]
```
$ terraform-docs --help
A utility to generate documentation from Terraform modules in various output formats

Usage:
  terraform-docs [command]

Available Commands:
  completion  Generate autocomplete for terraform-docs
  help        Help about any command
  json        Generate JSON of inputs and outputs
  markdown    Generate Markdown of inputs and outputs
  pretty      Generate colorized pretty of inputs and outputs
  tfvars      Generate terraform.tfvars of inputs
  version     Print the version number of terraform-docs
  xml         Generate XML of inputs and outputs
  yaml        Generate YAML of inputs and outputs

Flags:
      --header-from string             relative path of a file to read header from (default "main.tf")
  -h, --help                           help for terraform-docs
      --no-header                      do not show module header
      --no-inputs                      do not show inputs
      --no-outputs                     do not show outputs
      --no-providers                   do not show providers
      --no-requirements                do not show module requirements
      --no-sort                        do no sort items
      --output-values                  inject output values into outputs
      --output-values-from string      inject output values from file into outputs
      --sort-by-required               sort items by name and print required ones first
      --sort-inputs-by-required        [deprecated] use '--sort-by-required' instead
  -v, --version                        version for terraform-docs
      --with-aggregate-type-defaults   [deprecated] print default values of aggregate types

Use "terraform-docs [command] --help" for more information about a command.
```
and 
```
$ terraform-docs version
terraform-docs version v0.0.0- v0.9.1 darwin/amd64 BuildDate: 2020-04-03T02:30:49+0100
```

It likes this project is calling the deprecated options of terraform-docs, and not accepting their replacements.

**Comment by rquadling** [comment]
So use `--sort-inputs-by-required` instead.

**Comment by snolan-uturn** [comment]
> ```
> - repo: git://github.com/antonbabenko/pre-commit-terraform
>   rev: v1.29.0
>   hooks:
>     - id: terraform_validate
>     - id: terraform_fmt
>     - id: terraform_docs
>       args: ['--sort-by-required', '--no-providers']
> ```
> 
> is currently failing with the following error:
> 
> ```
> Terraform docs...........................................................Failed
> - hook id: terraform_docs
> - exit code: 1
> 
> getopt: unrecognized option '--sort-by-required'
> getopt: unrecognized option '--no-providers'
> ```
> 
> ```
> # terraform-docs -v
> terraform-docs version v0.0.0- v0.9.1 darwin/amd64
> ```
> 
> After a few failed attempts at digging in the scripts to figure out a fix, I am resorting to asking for competent help here.. :)

This should work:
```
- repo: git://github.com/antonbabenko/pre-commit-terraform
  rev: v1.29.0
  hooks:
    - id: terraform_validate
    - id: terraform_fmt
    - id: terraform_docs
      args:
        - '--args=--sort-by-required --no-providers'
```
