### ISSUE TITLE
terraform_docs not working in WSL

### ISSUE THREAD

**Issue by patpicos** [antonbabenko/pre-commit-terraform#107]
```
patrick@SRCD-PF1M03QG:/mnt/c/vscode/pega-on-azure/modules/azure_naming$ pre-commit run -a
Terraform fmt............................................................Passed
Terraform docs...........................................................Failed
- hook id: terraform_docs
- files were modified by this hook
```

Modified README.md:
```
# Usage
<!-- BEGINNING OF PRE-COMMIT-TERRAFORM DOCS HOOK -->
Error: Failed to read module directory: Module directory /tmp/terraform-docs-5n3p3DMqVj.tf does not exist or cannot be read.
<!-- END OF PRE-COMMIT-TERRAFORM DOCS HOOK -->
```
Version
```
patrick@SRCD-PF1M03QG:/mnt/c/vscode/pega-on-azure/modules/azure_naming$ terraform-docs -v
terraform-docs version v0.9.1 linux/amd64 BuildDate: 2020-05-07T14:00:18-04:00
```

## pre-commit-config.yaml
```
repos:
- repo: git://github.com/antonbabenko/pre-commit-terraform
  rev: v1.13.0 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
  hooks:
    - id: terraform_fmt
    - id: terraform_docs

```
```
