### ISSUE TITLE
README.md indentation issue on terraform_tflint hooks multiple arguments

### ISSUE THREAD

**Issue by os-virtualretail** [antonbabenko/pre-commit-terraform#113]
In order to pass multiple args, try the following:
    ```yaml
     - id: terraform_tflint
        args:
          - 'args=--deep'
          - 'args=--enable-rule=terraform_documented_variables'
    ```
should be 

    In order to pass multiple args, try the following:
    ```yaml
     - id: terraform_tflint
       args:
          - 'args=--deep'
          - 'args=--enable-rule=terraform_documented_variables'
    ```

there is one more space with args: so it fails. it needs to be aligned with previous line
