### ISSUE TITLE
terraform_docs_replace shows error although it works.

### ISSUE THREAD

**Issue by audunsolemdal** [antonbabenko/pre-commit-terraform#120]
Terraform version: 0.12.25
Tried both on Windows 10 and on WSL2 running Ubuntu 2004. Same result.
Valid for both the C-drive /mnt/c/... and pure Linux path.

Config: 
```
repos:
- repo: git://github.com/antonbabenko/pre-commit-terraform
  rev: v1.31.0 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
  hooks:
    - id: terraform_tfsec
    - id: terraform_fmt
    - id: terraform_docs_replace
    - id: terraform_tflint
```

I created my README docs with the terrafrom_docs_replace hook, it works great.
After updating my module and running the command, the docs are updated, yet I wrongfully(?) get the error message below. 

```
❯ pre-commit run -a
Terraform validate with tfsec............................................Passed
Terraform fmt............................................................Passed
Terraform docs (overwrite README.md).....................................Failed
- hook id: terraform_docs_replace
- files were modified by this hook
Terraform validate with tflint...........................................Passed
```

Which again causes my git commit to be blocked.
