### ISSUE TITLE
terraform_fmt.sh doesn't respect excludes

### ISSUE THREAD

**Issue by ericfrederich** [antonbabenko/pre-commit-terraform#121]
`pre-commit` has the ability to exclude files either globally or per hook.

The `terraform_fmt.sh` accepts a list of files to format.  However, it ends up simply running `terraform fmt` on the dirname of all the files.  This means if a file which is explicitly excluded in the `.pre-commit-config.yaml` file is sitting in the same directory as a file which is not excluded, it'll end up getting formatted.

The `terraform_fmt.sh` script should stop trying to be clever and simply run terraform fmt against the files explicitly handed to it and nothing more.

**Comment by ericfrederich** [comment]
Can someone review this?

**Comment by MaxymVlasov** [comment]
Works fine with the latest version

```yaml
repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.62.3
  hooks:
  - id: terraform_fmt
    exclude: environment\/.*$
```

`\.terraform\/.*$` excluded globally from Aug 2019
