### ISSUE TITLE
terraform-docs hook reporting error but changing readme.md correctly

### ISSUE THREAD

**Issue by vFondevilla** [antonbabenko/pre-commit-terraform#123]
When I have to modify the README.md in a module directory, always returns "Failed" but the file is correctly modified:

```
victor@Blckhl  ~/work/terraform/tf-rds-module   master ●  pre-commit run -a

Terraform fmt............................................................Passed
Terraform docs...........................................................Failed
- hook id: terraform_docs
- files were modified by this hook
```

Is this expected?
Running 1.31.0

**Comment by antonbabenko** [comment]
This is correct. It is `Failed` because `files were modified by this hook`. You should rerun it and it should become `Passed`.

**Comment by antonbabenko** [comment]
This issue has been resolved in version 1.62.1 :tada:

**Comment by marioanton** [comment]
mmm still happening in 1.62.3

**Comment by antonbabenko** [comment]
This issue has been resolved in version 1.63.0 :tada:

**Comment by antonbabenko** [comment]
This issue has been resolved in version 1.65.0 :tada:

**Comment by antonbabenko** [comment]
This issue has been resolved in version 1.67.0 :tada:

**Comment by suniilsync** [comment]
HI, 
After I added the _.pre-commit-config.yaml_ and ran the **pre-commit run -a**, it created the readme file and it ran successful, but while committing the terraform code to git, it run the checks and failed with the below error and code is not get commmit.

```
$ git ci -m "Added the pre-commit"
Terraform fmt............................................................ Passed
Terraform docs...........................................................Failed
- hook id: terraform_docs
- files were modified by this hook
```

multiple times I try to commit! I get the same error, please let me know if I am missing something 

This is the .pre-commit-config.yaml content

```
default_stages: [commit]
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.74.1
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
        args:
          - --hook-config=--path-to-file=README.md        # Valid UNIX path. I.e. ../TFDOC.md or docs/README.md etc.
          - --hook-config=--add-to-existing-file=true     # Boolean. true or false
          - --hook-config=--create-file-if-not-exist=true # Boolean. true or false
```
