### ISSUE TITLE
Args not passed to tfsec

### ISSUE THREAD

**Issue by mcaulifn** [antonbabenko/pre-commit-terraform#136]
I am attempting to disable color for all hooks as it is being run in Jenkins.

```yaml
repos:
- repo: git://github.com/antonbabenko/pre-commit-terraform
  rev: v1.32.0 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
  hooks:
    - id: terraform_fmt
    - id: terraform_docs
    - id: terraform_tfsec
      args: 
        - 'args=--no-color'
```
The `--no-color` arg is being ignored. It is honored when running tfsec directly.

**Comment by Gibby** [comment]
looks like -e is not being passed either

**Comment by robinbowes** [comment]
I believe this will be fixed by #142

**Comment by nkazarian-spokeo** [comment]
I think this is as expected...see [these](https://github.com/antonbabenko/pre-commit-terraform/blob/fe2d121d123cd3147d849dd0a825e534da976008/terraform_tfsec.sh#L54-L55) lines

Try `--args=` instead of `args=`

**Comment by nlamirault** [comment]
Works fine like that : 

```yaml
- repo: git://github.com/antonbabenko/pre-commit-terraform
  rev: v1.45.0
  hooks:
     - id: terraform_tfsec
      args:
      - '--args=--config-file .tfsec.yml'
```

**Comment by amontalban** [comment]
Anyone got it working?

I tried with:

```
      - id: terraform_tfsec
        args:
          - '--args=--concise-output'
          - '--args=--exclude-downloaded-modules'
```

But didn't work in `v1.47.0`.

**Comment by rtrive** [comment]
This doesn't work also in `v.1.48.0`

**Comment by pavloos** [comment]
@amontalban try  

```
        - id: terraform_tfsec
          args:
            - '-a --exclude-downloaded-modules --concise-output'
```

**Comment by amontalban** [comment]
> @amontalban try
> 
> ```
>         - id: terraform_tfsec
>           args:
>             - '-a --exclude-downloaded-modules --concise-output'
> ```

Thank you @pavloos that worked!

**Comment by rtrive** [comment]
```
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.48.0
    hooks:
      - id: terraform_fmt
      - id: terraform_tflint
      - id: terraform_tfsec
        args:
          - '-a --config-file ./tfsec.yml'
```
With the config suggest by @pavloos it gives me this error
`Failed to load the config file. stat ./tfsec.yml: no such file or directoryFailed to load the config file`.
Instead with absolute path of tfsec config file, it works.

**Comment by MaxymVlasov** [comment]
It works

```yaml
- repo: git://github.com/antonbabenko/pre-commit-terraform
  rev: v1.51.0
  hooks:
  - id: terraform_tfsec
    args:
      - --args=--no-color
```

**Comment by nlamirault** [comment]
Same error with v1.56.0 : 

```yaml
- id: terraform_tfsec
      args:
       - '--args=--config-file ./.tfsec.yml'
```
Output :

```
Terraform validate with tfsec............................................Failed
- hook id: terraform_tfsec
- exit code: 1

Error: failed to access config file './.tfsec.yml': stat ./.tfsec.yml: no such file or directory
Usage:
  tfsec [directory] [flags]
```

```
> cat ./.tfsec.yml
---
exclude:
  - AWS007
  - AZU009
  - GCP009
  - GCP010
  - GCP012
```
