### ISSUE TITLE
wrong arguments passed to terraform-docs (v0.10.0 and v0.10.1

### ISSUE THREAD

**Issue by aidan-melen** [antonbabenko/pre-commit-terraform#154]
Related: https://github.com/terraform-docs/terraform-docs/issues/324

```

**Comment by 1oglop1** [comment]
I'm not sure if this deserves it's own issue but I find argument parsing of `terraform-docs` broken in general.
I suspect this issue is of parsing arguments is related to the usage of https://github.com/agriffis/pure-getopt/ in `lib_getopt` file. After reading some SO posts it says that normal `getopts` stops parsing arguments after the  first `non-option` argument. And since `terraform-docs` are using `sub-commands` which are `non-option` arguments `getopt` or any other version of it is probably confused.

https://github.com/antonbabenko/pre-commit-terraform/blob/84374f64a05e53a23d8e23177db09ae964434f64/terraform_docs.sh#L30-L31



### This works
```
repos:

- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.43.0
  hooks:
    - id: terraform_docs
      args:
        - '--args=--hide-all'
```
The above snippet only works because `--hide-all` is a global argument.

### This does not


```
repos:

- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.43.0
  hooks:
    - id: terraform_docs
      args:
        - '--args=md document
```

 Neither this
```
repos:

- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.43.0
  hooks:
    - id: terraform_docs
      args:
        - 'md --indent=3 document'
```

While these 2 do not work because `md` and `document` are sub-commands (non-option arguments) 

This issue also prevents more granular configuration of `terraform-docs` without its config file.

So the challenge left here is to separate `.tf` files from a string like this `--hide-all md document main.tf output.tf` 
into
args `--hide-all md document` and files `main.tf output.tf` (which is basically what `parse_cmdline_` is trying to do)

**Comment by MaxymVlasov** [comment]
Bug for docker image confirmed

```yaml
repos:
- repo: git://github.com/antonbabenko/pre-commit-terraform
  rev: v1.50.0
  hooks:
    - id: terraform_docs
      language: docker_image
      entry: quay.io/terraform-docs/terraform-docs:0.15.0
```

The good news is that `pre-commit-terraform` with locally installed `terraform-docs` work fine.

```bash
$ terraform-docs -v
terraform-docs version v0.15.0 f3b6eab linux/amd64
```
 
```yaml
repos:
- repo: git://github.com/antonbabenko/pre-commit-terraform
  rev: v1.50.0
  hooks:
    - id: terraform_docs
```
