### ISSUE TITLE
How to run terraform-docs for code inside a sub folder

### ISSUE THREAD

**Issue by maulik-vimond** [antonbabenko/pre-commit-terraform#181]
I am trying to run terraform-docs hook for the terraform configuration inside a subfolder called "terraform". When I run `pre-commit run terraform_docs -a` no documentation is generated. The output says "Passed" for terraform docs. 

But if I run terraform-docs manually it works using `terraform-docs md ./terraform`

Here is my config file:
```
repos:
  - repo: https://github.com/talos-systems/conform
    rev: v0.1.0-alpha.20
    hooks:
      - id: conform
  - repo: git://github.com/antonbabenko/pre-commit-terraform
    rev: v1.47.0
    hooks:
    - id: terraform_fmt
    - id: terraform_docs
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: end-of-file-fixer
```

I am using,
pre-commit=`2.10.1`
terraform-docs=`0.11.2`
pre-commit-terraform=`1.47.0`
