### ISSUE TITLE
tflint: terraform_standard_module_structure for tfvars in a specific directory

### ISSUE THREAD

**Issue by bondezbond** [antonbabenko/pre-commit-terraform#184]
So I opened [this](https://github.com/terraform-linters/tflint/issues/1083) on tflint but I think the issues might be the script in this repo. tflint doesn't throw an error when I have a directory structure like this.

```
.
├── README.md
├── data.tf
├── inputs
│   ├── dev.tfvars
│   ├── prod.tfvars
│   └── stage.tfvars
├── main.tf
├── outputs.tf
├── variables.tf
└── versions.tf
```

When I run via `pre-commit run -a terraform_tflint` I get this error cause of my `inputs` directory

```
$ pre-commit run -a terraform_tflint
Terraform validate with tflint...........................................Failed
- hook id: terraform_tflint
- exit code: 3

4 issue(s) found:

Warning: terraform "required_version" attribute is required (terraform_required_version)

  on  line 0:
   (source code not available)

Reference: https://github.com/terraform-linters/tflint/blob/v0.23.1/docs/rules/terraform_required_version.md

Warning: Module should include a main.tf file as the primary entrypoint (terraform_standard_module_structure)

  on main.tf line 1:
   (source code not available)

Reference: https://github.com/terraform-linters/tflint/blob/v0.23.1/docs/rules/terraform_standard_module_structure.md

Warning: Module should include an empty outputs.tf file (terraform_standard_module_structure)

  on outputs.tf line 1:
   (source code not available)

Reference: https://github.com/terraform-linters/tflint/blob/v0.23.1/docs/rules/terraform_standard_module_structure.md

Warning: Module should include an empty variables.tf file (terraform_standard_module_structure)

  on variables.tf line 1:
   (source code not available)

Reference: https://github.com/terraform-linters/tflint/blob/v0.23.1/docs/rules/terraform_standard_module_structure.md

4 issue(s) found:

Warning: terraform "required_version" attribute is required (terraform_required_version)

  on  line 0:
   (source code not available)

Reference: https://github.com/terraform-linters/tflint/blob/v0.23.1/docs/rules/terraform_required_version.md

Warning: Module should include a main.tf file as the primary entrypoint (terraform_standard_module_structure)

  on main.tf line 1:
   (source code not available)

Reference: https://github.com/terraform-linters/tflint/blob/v0.23.1/docs/rules/terraform_standard_module_structure.md

Warning: Module should include an empty outputs.tf file (terraform_standard_module_structure)

  on outputs.tf line 1:
   (source code not available)

Reference: https://github.com/terraform-linters/tflint/blob/v0.23.1/docs/rules/terraform_standard_module_structure.md

Warning: Module should include an empty variables.tf file (terraform_standard_module_structure)

  on variables.tf line 1:
   (source code not available)

Reference: https://github.com/terraform-linters/tflint/blob/v0.23.1/docs/rules/terraform_standard_module_structure.md
```

.pre-commit.yaml
```
repos:
  - repo: git://github.com/antonbabenko/pre-commit-terraform
    rev: v1.48.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_docs
      - id: terraform_tflint
        args:
          - '--args=--only=terraform_deprecated_interpolation'
          - '--args=--only=terraform_deprecated_index'
          - '--args=--only=terraform_unused_declarations'
          - '--args=--only=terraform_comment_syntax'
          - '--args=--only=terraform_documented_outputs'
          - '--args=--only=terraform_documented_variables'
          - '--args=--only=terraform_typed_variables'
          - '--args=--only=terraform_module_pinned_source'
          - '--args=--only=terraform_naming_convention'
          - '--args=--only=terraform_required_version'
          - '--args=--only=terraform_required_providers'
          - '--args=--only=terraform_standard_module_structure'
          - '--args=--only=terraform_workspace_remote'
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-merge-conflict
```

**Comment by antonbabenko** [comment]
Hi @bondezbond !

The reason why you see this behavior is that `terraform_tflint` hook watches for changes in `tf` and `tfvars` files (https://github.com/antonbabenko/pre-commit-terraform/blob/master/.pre-commit-hooks.yaml#L50).

You can edit your `.pre-commit.yaml` and add `files` to trigger this hook only on certain files, for eg:
```yaml
repos:
  - repo: git://github.com/antonbabenko/pre-commit-terraform
    rev: v1.48.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_docs
      - id: terraform_tflint
        files: \.tf$   # <= or something like this
        args:
          - '--args=--only=terraform_deprecated_interpolation'
```

More details - https://pre-commit.com/#filtering-files-with-types
