### ISSUE TITLE
Allow to specify the version of terraform-docs for the hook to use

### ISSUE THREAD

**Issue by antonbabenko** [antonbabenko/pre-commit-terraform#188]
Currently, `terraform_docs` (and similar) hooks will use the version of `terraform-docs` installed on the system.

With each major release of the `terraform-docs` the output format changes and users need to regenerate the docs.

We need to be able to pin a specific version in the hook so that we have more control over `README.md`.

## Proposal:
- Use `args` to define a specific version of docker image - https://terraform-docs.io/user-guide/installation/#docker

## Sample:
```yaml
repos:
  - repo: git://github.com/antonbabenko/pre-commit-terraform
    rev: v1.48.0
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
        args: ['--version=0.12']
```
