### ISSUE TITLE
TFSec Outputs The Same Results Multiple Times

### ISSUE THREAD

**Issue by sharkymcdongles** [antonbabenko/pre-commit-terraform#196]
When I add tfsec as a hook it outputs the same results 2x for some reason, and I can't seem to figure out why. Anyone else experiencing this? I am using latest tfsec and the latest release hash from this repo. My configuration file is:

```
---
repos:
- repo: git://github.com/antonbabenko/pre-commit-terraform
  rev: fa3859e
  hooks:
  - id: terraform_fmt
  - id: terraform_validate
  - id: terraform_tflint
  - id: terraform_tfsec
  - id: terraform_docs_replace
```

I am also using the latest precommit.
