### ISSUE TITLE
Add possibility to generate hcl files with terraform-docs

### ISSUE THREAD

**Issue by lays147** [antonbabenko/pre-commit-terraform#199]
When using the `terraform_docs` hook I'm not able to generate the hcl file based on this setup:
```yml
repos:
    - repo: git://github.com/antonbabenko/pre-commit-terraform
      rev: v1.50.0 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
      hooks:
          - id: terraform_fmt
          - id: terraform_docs
          - id: terraform_docs
            args:
                [
                    "tfvars",
                    "hcl",
                    "--output-file",
                    "terraform.tfvars.model",
                    ".",
                ]
          - id: terraform_tflint
          - id: terraform_tfsec
```
```sh
➜  ecs-service-module git:(master) ✗ pre-commit run -a
Terraform fmt............................................................Passed
Terraform docs...........................................................Passed
Terraform docs...........................................................Failed
- hook id: terraform_docs
- exit code: 1

getopt: unrecognized option '--output-file'

Terraform validate with tflint...........................................Passed
Terraform validate with tfsec............................................Passed
```

Is it possible to add the possibility to generate the hcl, since apparently the command for `terraform_tfdocs` is directly connected with the markdown generation?
