### ISSUE TITLE
Provider markdown pins seem to change in action but not locally

### ISSUE THREAD

**Issue by nitrocode** [antonbabenko/pre-commit-terraform#205]
Edit: It's a terraform-docs issue https://github.com/terraform-docs/terraform-docs/issues/517

Using the latest `1.50.0` (and `1.48.0`) of this action

```yaml
repos:
  - repo: git://github.com/antonbabenko/pre-commit-terraform
    rev: v1.50.0
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
```

Using the latest `0.14.1` of `terraform-docs` locally and in github actions

I see this in [our github action CI](https://github.com/cloudposse/terraform-aws-components/pull/330/checks?check_run_id=2842467587) (hard coded number to tilde) and the EXACT opposite (tilde to hard coded number) when I run it locally

![image](https://user-images.githubusercontent.com/7775707/122282715-b96afc00-ceb9-11eb-95c5-24355659eb4c.png)

We didn't see this before until very recently which makes me believe that it may be a terraform-docs issue. Perhaps once this issue https://github.com/antonbabenko/pre-commit-terraform/issues/188 is resolved, we can pin down the version... if the version of terraform-docs is the issue.
