### ISSUE TITLE
Invalid option terraform_fmt.sh

### ISSUE THREAD

**Issue by nadworny** [antonbabenko/pre-commit-terraform#207]
# Problem
During `pre-commit run -a` I'm getting the following error:

```
Terraform fmt............................................................Failed
- hook id: terraform_fmt
- exit code: 2

: invalid optionadworny/.cache/pre-commit/repot5f0ochh/terraform_fmt.sh: line 2: set: -
set: usage: set [--abefhkmnptuvxBCHP] [-o option] [arg ...]
```

My .pre-commit-config.yml:
```yaml
exclude: '(^.+\.log$)'
repos:
  -  repo: https://github.com/antonbabenko/pre-commit-terraform
     rev: v1.50.0
     hooks:
       -  id: terraform_fmt
```

# Workaround
It seems to be somehow related to the new lines problem as after executing `dos2unix terraform_fmt.sh` everything works fine (see https://askubuntu.com/questions/1044280/set-eo-pipefail-not-working-in-windows-subsystem-for-linux-ubuntu-16-04 and https://github.com/antonbabenko/pre-commit-terraform/issues/204)

# Environment
![image](https://user-images.githubusercontent.com/1425919/123436910-6a1a7f00-d5cf-11eb-98a3-4f3abf2fa84e.png)
GNU bash, version 5.1.8(1)-release (x86_64-apple-darwin20.3.0)
pre-commit 2.13.0
