### ISSUE TITLE
Checkov - unable to skip a check

### ISSUE THREAD

**Issue by kelechi-i** [antonbabenko/pre-commit-terraform#208]
`.pre-commit-config.yaml`

```yaml
- repo: git://github.com/antonbabenko/pre-commit-terraform
  rev: v1.49.0
  hooks:
    - id: terraform_validate
      args:
        - '--args=-json'
    - id: terraform_tflint
    - id: terraform_tfsec    
    - id: checkov
      args:     
        [-d . --skip-check CKV_AWS_24]
```

When I run the `pre-commit run -a`  command locally, the checkov rule CKV_AWS_24 rule is not skipped. How do I skip multiple checkov rules?

Checkov version 1.0.855

**Comment by MaxymVlasov** [comment]
Hi, @kelechi-i.

For `checkov` you need to specify each argument separately

```yaml
repos:
- repo: git://github.com/antonbabenko/pre-commit-terraform
  rev: v1.50.0
  hooks:
  - id: checkov
    args: [
      "-d", ".",
      "--skip-check", "CKV2_AWS_8",
    ]
```


---

Can be fixed together with #199
TBD: Add/clarify doc how to use arguments with `checkov`
