### ISSUE TITLE
Disabling `--lockfile` for `terraform_docs`

### ISSUE THREAD

**Issue by nitrocode** [antonbabenko/pre-commit-terraform#212]
I'm using the latest [terraform-docs](https://github.com/terraform-docs/terraform-docs/releases/tag/v0.15.0) 0.15.0 which adds a way to disable reading the lockfile.

Locally this works
```shell
$ terraform-docs --version
terraform-docs version v0.15.0 darwin/amd64
$ terraform-docs md --lockfile=false .
```

I tried setting the following

```yaml
repos:
  - repo: git://github.com/antonbabenko/pre-commit-terraform
    rev: v1.50.0
    hooks:
      - id: terraform_docs
        args: ['--lockfile=false']
```

When the pre-commit hook runs, I get the following error

```shell
✗ git commit -m 'test'
Terraform docs...........................................................Failed
- hook id: terraform_docs
- exit code: 1

getopt: unrecognized option '--lockfile=false'
```

How do I set this correctly ?

I also tried setting a `.terraform.docs.yml` in the root of my repo but this doesn't seem to be consumed by the `pre-commit`.

```yaml
settings:
  lockfile: false
```

**Comment by antonbabenko** [comment]
Hi,

I have not tried it myself yet but you can try it like it is described for [`terraform_tflint`](https://github.com/antonbabenko/pre-commit-terraform#notes-about-terraform_tflint-hooks):
```
repos:
  - repo: git://github.com/antonbabenko/pre-commit-terraform
    rev: v1.50.0
    hooks:
      - id: terraform_docs
        args: ['--args=--lockfile=false']
```
