### ISSUE TITLE
"No files to check" - using '-recursive' for terraform_fmt

### ISSUE THREAD

**Issue by ryanpodonnell1** [antonbabenko/pre-commit-terraform#214]
## Problem:

I have multiple tf directories for modules and would like to run a `terraform fmt -recursive` against all dirs rather than calling out the dirs individually

## Expected behavior:
```
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.50.0 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
    hooks:
      - id: terraform_fmt
        args:
          - "--args=-recursive"
```

runs terraform fmt against the root dir and child module dirs

## Actual Behavior 

While running in root git dir:

```
└─▪ pre-commit run terraform_fmt
Terraform fmt........................................(no files to check)Skipped
```

## To recreate/test

Create a module dir structure with unformatted terraform files:
```
.git
<root_files>
./modules/s3/*.tf
./modules/kms/*.tf
```

**Comment by MaxymVlasov** [comment]
Hi @ryanpodonnell1 
You need to run `pre-commit run terraform_fmt --all-files`

And you don't need
```yaml
        args:
          - "--args=-recursive"
```
pre-commit runs only on changed files, by default.

**Comment by NicholasRaymondiSpot** [comment]
I know it's been awhile since this topic has been touched, but I'm having a similar configuration conundrum. I have one `.pre-commit-config.yaml` in the root of our repo configured for using `terraform fmt` and `tflint`:

```
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: "v1.83.5"
    hooks:
      - id: terraform_fmt
        args:
        - --args=-recursive
      - id: terraform_tflint
        args:
        - --args=--recursive
```

Here's the breakdown of our TF structure, there's a few subdirectories I wanted to recursively check through:

```
accounts
├── dev
 │   └── main.tf
 │   └── outputs.tf
 │   └── variables.tf
├── stage
 │   └── main.tf
 │   └── outputs.tf
 │   └── variables.tf
├── modules
 │   └── eks
 │    |     └── main.tf
 │    |     └── outputs.tf
 │    |     └── variables.tf
 │   └── serviceaccount
 │    |     └── main.tf
 │    |     └── outputs.tf
 │    |     └── variables.tf
└── .pre-commit-config.yaml
```

My goal here was to not have to coach our engineers to run the `pre-commit run terraform_fmt --all-files` command everytime they make a repo change. I want them to just run `pre-commit install` from the root of the repo once and now everytime they commit a new change to any of the dev/stage/modules configs, on `git commit` all of these files are checked and evaluated. However it seems the options are ignored and only the root is being examined when commits are made:

```
Terraform fmt........................................(no files to check)Skipped
Terraform validate with tflint.......................(no files to check)Skipped
````

Is there a better way to do this than configuring an alias for `pre-commit run terraform_fmt --all-files`?
