### ISSUE TITLE
Add a check for specific version of a tool before applying a hook

### ISSUE THREAD

**Issue by antonbabenko** [antonbabenko/pre-commit-terraform#246]
### What problem are you facing?

It would be helpful to be able to set hard requirements on the version of certain tools (e.g. `terraform-docs`) inside the YAML config so that the hook fails&stops if the version mismatches at the very beginning.

### How could pre-commit-terraform help solve your problem?

Potential config:

```yaml
- id: terraform_docs
  args:
    - TERRAFORM_DOCS_ALLOWED_VERSION_REGEXP="0.13.[0-9]+"
    - tfvars hcl --output-file terraform.tfvars.model .
```

I think it should be applied to `terraform_docs` hooks first of all.

Ref: https://tldp.org/LDP/abs/html/bashver3.html#REGEXMATCHREF
