### ISSUE TITLE
terraform_docs_replace does not work in root directory

### ISSUE THREAD

**Issue by antonbabenko** [antonbabenko/pre-commit-terraform#29]
`.pre-commit-config.yaml`:
```
repos:
- repo: git://github.com/antonbabenko/pre-commit-terraform
  rev: v1.8.0
  hooks:
    - id: terraform_fmt
    - id: terraform_docs_replace
      args: ['--with-aggregate-type-defaults', '--sort-inputs-by-required']
```

There are *.tf and *.tfvars files in root and in directories.

README.md in directories is correct, but README.md in the root dir has this content:
```
Usage:
    terraform-docs [--no-required] [--no-sort | --sort-inputs-by-required] [--with-aggregate-type-defaults] [json | markdown | md] <path>...
```

PS: @RothAndrew could you please take a look and fix this.
