### ISSUE TITLE
Variable expansion in infracost

### ISSUE THREAD

**Issue by djtecha** [antonbabenko/pre-commit-terraform#334]
I am trying to use the infracost pre-commit hook and wondering if there was a way to mimick the FR in this issue: https://github.com/antonbabenko/pre-commit-terraform/pull/264

Trying to use the macros so I can have specific config files per project and it appears to not be expanding the __GIT_WORKING_DIR__ variable.

```
repos:
- repo: git://github.com/antonbabenko/pre-commit-terraform
  rev: v1.62.3
  hooks:
    - id: infracost_breakdown
      args:
        - --args=--config-file=__GIT_WORKING_DIR__/infracost.yml
      verbose: true

**Comment by antonbabenko** [comment]
@MaxymVlasov Could you put your infracost ~hat~ socks and take a look at this one?

**Comment by MaxymVlasov** [comment]
Hmm, can you provide an example where you need `GIT_WORKING_DIR`? Because it works fine without that var.

`.pre-commit-config.yaml`:
```yaml
repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.64.0
  hooks:
    - id: infracost_breakdown
      args:
        - --args=--config-file=infracost.yml
        # - --args=--path=./environment/qa
        - --hook-config='.totalHourlyCost >= 0.1'
        - --hook-config=".totalHourlyCost|tonumber > 1"
        - -h ".projects[].diff.totalMonthlyCost|tonumber!=10000"
        - -h [.projects[].diff.totalMonthlyCost | select (.!=null) | tonumber] | add > 1000
      verbose: true # Always show costs
```

`infracost.yml`:
```yaml
version: 0.1

projects:
  - path: ./environment/qa
```

Feel free to reopen the issue.

**Comment by djtecha** [comment]
Is that infracost.yml in the top level dir? Because I think I need to create specific ones per TF workspace. So if I edit a file in something like ops/stg/main.tf it would trigger the infracost and use the config file found in ops/stg/infracost.yaml

**Comment by djtecha** [comment]
Sry I've been negligent here. Finally had some time to circle back to this and maybe I'm misunderstanding how this should be designed. Say I had multiple workspaces that existed in the same repo like this:

workspace/
  serviceA/
    prod/
    stg/
  serviceB/
    prod/
    stg/


And I wanted infracost to run anytime a file a was changed in a SERVICE/ENV dir. How would I structure this if I have different AWS profiles I need to sue depending on ENV? Trying your method still requires me to have a block defining the config file in my top level pre-commit-config.yaml and it would run that against every service every time which isn't entirely needed.

**Comment by djtecha** [comment]
Ok, maybe I get this. So I should jsut refference 1 infracost.yaml file that has a large set of `projects` defined (have a script that can generate this) Then those runs only get triggered on a file change.

```
# infracost.yml
version: 0.1
projects:
  - path: workspace/ops/stg
    env:
      AWS_PROFILE: stg
  - path: workspace/tf_test/stg
    env:
      AWS_PROFILE: stg
  - path: workspace/test_2/stg
    env:
      AWS_PROFILE: stg
```
