### ISSUE TITLE
[Question] What regex do I need to ignore a very specific folder in my repo, but NOT the underlying directories?

### ISSUE THREAD

**Issue by spkane** [antonbabenko/pre-commit-terraform#391]
In this case, I need to ignore `environments/cluster-sandbox/`, but not the directories underneath it. That directory has an `*.auto.tfvars` file in it, which causes `tflint` to assume that it is a terraform directory, but in reality, that file is simply linked into some other locations lower down.

I tried a few regex approaches, but none of them seemed to work quite right.

Thanks!

**Comment by yermulnik** [comment]
@spkane Which regex'es did you try?
Using https://github.com/antonbabenko/pre-commit-terraform/blob/master/.pre-commit-hooks.yaml#L70 as base I'd try something like the below:
```
  exclude: (\.terraform\/.*|^environments/cluster-sandbox/?)$
```
(assuming the `environments/cluster-sandbox/` dir is based in the root of your repo with `pre-commit-terraform` enabled)

**Comment by yermulnik** [comment]
Ref: https://pre-commit.com/#regular-expressions

**Comment by spkane** [comment]
So, at the moment I have this:

```yaml
    - id: terraform_tflint
      args:
      - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
      - --args=--module
      files: (\.tf|\.tfvars)$
      exclude: (\.terraform.*|k8s.*|^environments/cluster-sandbox/?)$
```

The dir `environments/cluster-sandbox/` has a file called `account.auto.tfvars` and some directories with various terraform code in them.

When I add `\.tfvars` to the **files:** option `tflint` runs in that directory despite it the fact that I think the regex should exclude it.

I have only *sort of* achieved the behavior I want by removing `\.tfvars` from the **files:** option, but I really want it to include those files, just not in this one location.

**Comment by yermulnik** [comment]
I'm not quite familiar with such use cases so I'm sort of guessing. I assume you want to skip the `environments/cluster-sandbox/` while process its subdirs, right?
Try something like this (despite it's more of a task unrelated to `pre-commit-terraform` but instead related to https://pre-commit.com/ and https://docs.python.org/3/library/re.html#regular-expression-syntax):
```
exclude: (\.terraform.*|k8s.*|^environments/cluster-sandbox/[^/]+)$
```
What I'm trying to say is that you'd need to create a regex to exclude exactly what you don't need to be included.
You also may want to look into other filtering options provided by `pre-commit`: https://pre-commit.com/#filtering-files-with-types

**Comment by spkane** [comment]
That worked. Thank you. Regex can be a bit of a mystical art at times.

**Comment by yermulnik** [comment]
Cheers @spkane. Glad I came in useful =)

**Comment by MaxymVlasov** [comment]
Just in case, you can simplify your hook config because part of the things already set's by default

https://github.com/antonbabenko/pre-commit-terraform/blob/4619ee245c65077a86d931c2f9d5663475720c74/.pre-commit-hooks.yaml#L63-L70


```yaml
    - id: terraform_tflint
      args:
      - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
      - --args=--module
      exclude: (k8s.*|^environments/cluster-sandbox/[^/]+)$
```
