### ISSUE TITLE
Failed to parse CLI arguments; Failed to load `service-account.tf`: Multiple files in different directories are not allowed

### ISSUE THREAD

**Issue by simtcrom** [antonbabenko/pre-commit-terraform#394]
### Describe the bug

.pre-commit-config.yaml

```yaml
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: "v1.72.1"
    hooks:
      - id: terraform_fmt
        entry: terraform fmt -recursive
        language: system
        pass_filenames: false
      - id: terraform_docs
        entry: 'terraform-docs markdown .'
        args:
        - --output-file=README.md
        language: system
        pass_filenames: false
      - id: terraform_tflint
        entry: tflint
        language: system
```

when I do,

```
PS C:\Users> git commit -m "added terradocs"
Terraform fmt............................................................Passed
Terraform docs...........................................................Passed
Terraform validate with tflint...........................................Failed
- hook id: terraform_tflint
- exit code: 1


Failed to parse CLI arguments; Failed to load `service-account.tf`: Multiple files in different directories are not allowed
```

I have service-account.tf at the folder where I run commit

Any thoughts?

### Environment information

```
OS: Win10 with Ubuntu 18.04 on WSL2

~$ uname -a
Linux xxxxxxxxxxx 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

PS C:\Users> pre-commit --version
pre-commit 2.19.0

PS C:\Users> terraform --version
Terraform v0.15.5
on windows_amd64

PS C:\Users> python --version
Python 3.8.10

PS C:\Users> terraform-docs --version
terraform-docs version v0.16.0 1f686b1 windows/amd64

PS C:\Users> tflint --version
TFLint version 0.37.0
```
