### ISSUE TITLE
All hooks skipped when using steps from the README

### ISSUE THREAD

**Issue by shadycuz** [antonbabenko/pre-commit-terraform#403]
### Describe the bug

When running the install steps from the README all checks are skipped even when running `pre-commit run -a`. Likely an issue in `pre-commit`? 

### How can we reproduce it?

Create the `.pre-config.yaml` file from the README or one similar.
```yml
repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.73.0 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
  hooks:
    - id: terraform_fmt
    - id: terraform_docs
    - id: terraform_checkov
```
Run the command from the README
```console
vscode@bd2bb74cebdc:/workspaces/terraform-module-template$ pre-commit run -a
Terraform fmt........................................(no files to check)Skipped
Terraform docs.......................................(no files to check)Skipped
Checkov..............................................(no files to check)Skipped
```
All checks are skipped. 

### Environment information

* OS:  Ubuntu 22.04 on WSL2

* `uname -a` and/or `systeminfo | Select-String "^OS"` output:

```bash
Linux bd2bb74cebdc 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

* Tools availability and versions:

```bash
pre-commit 2.19.0
Terraform v1.2.4
python SKIPPED
Python 3.10.4
checkov 2.1.25
terraform-docs version v0.16.0 linux/amd64
terragrunt SKIPPED
terrascan terrascan SKIPPED
TFLint version 0.38.1
+ ruleset.aws (0.14.0)
tfsec You are running a locally built version of tfsec.
```

* `.pre-commit-config.yaml`:

<details><summary>file content</summary>

```yml
repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.73.0 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
  hooks:
    - id: terraform_fmt
    - id: terraform_docs
    - id: terraform_checkov
```

</details>
