### ISSUE TITLE
terraform_docs fails when using release v.1.7.4

### ISSUE THREAD

**Issue by ausfestivus** [antonbabenko/pre-commit-terraform#413]
### Describe the bug

When running the `tf_docs` hook with release v1.7.4, the hook fails with:

```
Terraform docs...........................................................Failed
- hook id: terraform_docs
- exit code: 1
```

### How can we reproduce it?

Run the `tf_docs` hook with v1.7.3 and witness success.
Run the `tf_docs` hook with v1.7.4 and witness failure.

### Environment information

* OS: macOS 12.4

* Tools availability and versions:

```bash
pre-commit 2.20.0
Terraform v1.2.4
python SKIPPED
Python 3.9.13
checkov checkov SKIPPED
terraform-docs version v0.16.0 darwin/amd64
terragrunt SKIPPED
terrascan version: v1.15.2
TFLint version 0.38.1
tfsec v1.26.3
```

* `.pre-commit-config.yaml`:

<details><summary>file content</summary>

```yaml
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.73.0
    hooks:
      - id: tfupdate
      - id: terraform_docs
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_providers_lock
```

</details>
