### ISSUE TITLE
Cannot run tflint recursively

### ISSUE THREAD

**Issue by Smana** [antonbabenko/pre-commit-terraform#416]
### Describe the bug

I'm trying to use the `tflint` hook and I cannot get it work in a recursive mode. I didn't find the root cause yet.

### How can we reproduce it?

Here is the `.pre-commit-config.yaml`
```yaml
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform.git
    rev: v1.74.0
    hooks:
      - id: terraform_fmt
      - id: terraform_tflint
        args:
          - --args=--init
          - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
```

and the `.tflint.hcl`
```hcl
config {
  module = true
}
plugin "aws" {
  enabled    = true
  deep_check = true
  source     = "github.com/terraform-linters/tflint-ruleset-aws"
  version    = "0.14.0"
}
```

When I run the command from the root directory of the repository it doesn't throw any error.
```console
pre-commit run --all
[INFO] Initializing environment for https://github.com/antonbabenko/pre-commit-terraform.git.
Terraform fmt............................................................Passed
Terraform validate with tflint...........................................Passed
```

If I run the tflint command from a test module as follows it works:
```console
tflint --config=../../.tflint.hcl
2 issue(s) found:

Error: "t1.medium" is an invalid value as instance_type (aws_instance_invalid_type)

  on main.tf line 3:
   3:   instance_type = "t1.medium"

Warning: "t1.medium" is previous generation instance type. (aws_instance_previous_type)

  on main.tf line 3:
   3:   instance_type = "t1.medium"

Reference: https://github.com/terraform-linters/tflint-ruleset-aws/blob/v0.14.0/docs/rules/aws_instance_previous_type.md
```

### Environment information

* Docker image: ubuntu:jammy-20220421
* tflint version v0.37.0
* pre-commit version 2.18.1

Any help would be welcome, I'm probably missing something obvious to you :)
