### ISSUE TITLE
How do use a specific terraform version?

### ISSUE THREAD

**Issue by simonweil** [antonbabenko/pre-commit-terraform#427]
I use version 1.1.6, I can't see how to define this version to make validate work

Thanks for all you work!

**Comment by yermulnik** [comment]
- Put TF 1.1.6 into your PATH env var as `terraform` before any other occurence of `terraform` binary. Might want to leverage https://github.com/warrensbox/terraform-switcher to streamline this on a per project basis.
- Build your own Docker image with a specific version of Terraform: https://github.com/antonbabenko/pre-commit-terraform/blob/master/Dockerfile#L14
- Pull existing tag  which fits your needs from Dockerhub: https://github.com/antonbabenko/pre-commit-terraform#1-install-dependencies

Does any of above make sense?

**Comment by simonweil** [comment]
Hmmm, I forgot to mention that I'm using it in GHA.
How can I do it in that context?

**Comment by yermulnik** [comment]
Apart from using `pre-commit` as `post-push` being a bit controversy to me, you might want to look into setting up Terraform within GH action like e.g. https://github.com/hashicorp/setup-terraform, which would help to run Terraform version of your desire.
There seem to exist plenty of others alike GH actions in the wild, so you might want to check those and pitch upon the one that fulfils your requirements best.

**Comment by yermulnik** [comment]
Please let me know if this helps and we can close this issue out.

**Comment by simonweil** [comment]
I'm fine with using [hashicorp/setup-terraform](https://github.com/hashicorp/setup-terraform), if you have an example usage with multiple modules that would be great

**Comment by simonweil** [comment]
I managed to set it up like this:
```yml
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.6
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -recursive -check
      - name: Terraform init & validate
        id: validate
        run: |
          base_dir="$(pwd)"
          for tf_dir in $(find . -type f -name '*.tf' -printf '%h\n' | sort -u | grep -v '/.terraform/'); do
            cd "$base_dir/$tf_dir"
            echo
            echo "----------------------"
            echo "Running in $tf_dir...."
            echo "----------------------"
            echo
            terraform init -backend=false
            terraform validate

```

Thanks for the help!
