### ISSUE TITLE
tflint 0.40.0 changes seem to break current terraform_tflint hook configuration

### ISSUE THREAD

**Issue by tofupup** [antonbabenko/pre-commit-terraform#434]
### Describe the bug

`tflint` release 0.40.0 made some [breaking changes](https://github.com/terraform-linters/tflint/releases/tag/v0.40.0) that look to impact how it uses `--only` CLI options to specify rules.  I've opened issue https://github.com/terraform-linters/tflint/issues/1513 to see if this is a bug that they will fix, or if `pre-commit-terraform` will need to modify the `terraform_tflint` hook to accommodate future versions.

Short summary is `tflint` has rolled the `terraform` plugin into the released binary, and now support an option in the configuration file to enable either [`all` or `recommended` rules](https://github.com/terraform-linters/tflint-ruleset-terraform/blob/v0.1.0/docs/rules/README.md).  By default, with no configuration file, it will go with `recommended`.   However, if you run `tflint` 0.40.0 with `--only=terraform_naming_convention` (not a rule part of the `recommended` set), the rule does not get run.  If you use the `all` rule preset in the `tflint` configuration file, the `--only=` option gets ignored and all rules are run.

Once I get a response on the `tflint` issue, I'll update here if it looks like changes will be needed.  In the interim, if a new docker container is built automatically, it will include `tflint` 0.40.0, which will no longer run all of the tests expected in `terraform_tflint`.   Pinning the `tflint` version in the github workflows might be considered until a response in the [`tflint` issue](https://github.com/terraform-linters/tflint/issues/1513).

### How can we reproduce it?

Update `tflint` to 0.40.0 and run `pre-commit run -a terraform_tflint` on a file that will trigger rules not in the `recommended` list.

<details><summary>Files</summary>
`private-codecommit-repo/main.tf`

```hcl
module "private-codecommit-repo" {
  source = "git::ssh://SOMEUSER@git-codecommit.us-east-2.amazonaws.com/v1/repos/private-codecommit-repo"
}

variable "var1" {
  type = string
}
```

`.pre-commit-config.yaml`:

```yaml
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.75.0
    hooks:
      - id: terraform_fmt
      - id: terraform_wrapper_module_for_each
      - id: terraform_validate
      - id: terraform_docs
        args:
          - '--args=--lockfile=false'
      - id: terraform_tflint
        args:
          - '--args=--only=terraform_deprecated_interpolation'
          - '--args=--only=terraform_deprecated_index'
          - '--args=--only=terraform_unused_declarations'
          - '--args=--only=terraform_comment_syntax'
          - '--args=--only=terraform_documented_outputs'
          - '--args=--only=terraform_documented_variables'
          - '--args=--only=terraform_typed_variables'
          - '--args=--only=terraform_module_pinned_source'
          - '--args=--only=terraform_naming_convention'
          - '--args=--only=terraform_required_version'
          - '--args=--only=terraform_required_providers'
          - '--args=--only=terraform_standard_module_structure'
          - '--args=--only=terraform_workspace_remote'
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
```
</details>

<details><summary>terraform_tflint with tflint 0.39.3</summary>

```bash
❯ sudo ln -s /usr/bin/tflint-0.39.3 /usr/bin/tflint
❯ tflint -v
TFLint version 0.39.3

❯ pre-commit run -a terraform_tflint
Terraform validate with tflint...........................................Failed
- hook id: terraform_tflint
- exit code: 2

Command 'tflint --init' successfully done:




TFLint in private-codecommit-repo/:
7 issue(s) found:

Warning: terraform "required_version" attribute is required (terraform_required_version)

  on  line 0:
   (source code not available)

Reference: https://github.com/terraform-linters/tflint/blob/v0.39.3/docs/rules/terraform_required_version.md

Notice: module name `private-codecommit-repo` must match the following format: snake_case (terraform_naming_convention)

  on main.tf line 1:
   1: module "private-codecommit-repo" {

Reference: https://github.com/terraform-linters/tflint/blob/v0.39.3/docs/rules/terraform_naming_convention.md

Warning: Module source "git::ssh://SOMEUSER@git-codecommit.us-east-2.amazonaws.com/v1/repos/private-codecommit-repo" is not pinned (terraform_module_pinned_source)

  on main.tf line 2:
   2:   source = "git::ssh://SOMEUSER@git-codecommit.us-east-2.amazonaws.com/v1/repos/private-codecommit-repo"

Reference: https://github.com/terraform-linters/tflint/blob/v0.39.3/docs/rules/terraform_module_pinned_source.md

Notice: `var1` variable has no description (terraform_documented_variables)

  on main.tf line 5:
   5: variable "var1" {

Reference: https://github.com/terraform-linters/tflint/blob/v0.39.3/docs/rules/terraform_documented_variables.md

Warning: variable "var1" should be moved from main.tf to variables.tf (terraform_standard_module_structure)

  on main.tf line 5:
   5: variable "var1" {

Reference: https://github.com/terraform-linters/tflint/blob/v0.39.3/docs/rules/terraform_standard_module_structure.md

Warning: variable "var1" is declared but not used (terraform_unused_declarations)

  on main.tf line 5:
   5: variable "var1" {

Reference: https://github.com/terraform-linters/tflint/blob/v0.39.3/docs/rules/terraform_unused_declarations.md

Warning: Module should include an empty outputs.tf file (terraform_standard_module_structure)

  on outputs.tf line 1:
   (source code not available)

Reference: https://github.com/terraform-linters/tflint/blob/v0.39.3/docs/rules/terraform_standard_module_structure.md
```

</details>

<details><summary>terraform_tflint with tflint 0.40.0</summary>

```bash
❯ sudo rm /usr/bin/tflint
❯ sudo ln -s /usr/bin/tflint-0.40.0 /usr/bin/tflint
❯ tflint -v
TFLint version 0.40.0
+ ruleset.terraform (0.1.0-bundled)
❯ pre-commit run -a terraform_tflint
Terraform validate with tflint...........................................Failed
- hook id: terraform_tflint
- exit code: 2

Command 'tflint --init' successfully done:




TFLint in private-codecommit-repo/:
3 issue(s) found:

Warning: terraform "required_version" attribute is required (terraform_required_version)

  on  line 0:
   (source code not available)

Reference: https://github.com/terraform-linters/tflint-ruleset-terraform/blob/v0.1.0/docs/rules/terraform_required_version.md

Warning: Module source "git::ssh://SOMEUSER@git-codecommit.us-east-2.amazonaws.com/v1/repos/private-codecommit-repo" is not pinned (terraform_module_pinned_source)

  on main.tf line 2:
   2:   source = "git::ssh://SOMEUSER@git-codecommit.us-east-2.amazonaws.com/v1/repos/private-codecommit-repo"

Reference: https://github.com/terraform-linters/tflint-ruleset-terraform/blob/v0.1.0/docs/rules/terraform_module_pinned_source.md

Warning: variable "var1" is declared but not used (terraform_unused_declarations)

  on main.tf line 5:
   5: variable "var1" {

Reference: https://github.com/terraform-linters/tflint-ruleset-terraform/blob/v0.1.0/docs/rules/terraform_unused_declarations.md
```

</details>

### Environment information

* OS:  VSCode devcontainer based on Ubuntu 22.04 on WSL2

* `uname -a` and/or `systeminfo | Select-String "^OS"` output: 

```bash
❯ uname -a
Linux efc04b3806ca 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

* Tools availability and versions:

```bash
GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)
pre-commit 2.20.0
Terraform v1.2.8
Python 3.10.4
Python 3.10.4
checkov 2.1.204
terraform-docs version v0.16.0 1f686b1 linux/amd64
terragrunt version v0.38.9
terrascan version: v1.15.2
TFLint version 0.40.0
+ ruleset.terraform (0.1.0-bundled)
tfsec v1.27.6
tfupdate 0.6.7
hcledit 0.2.6
```

* `.pre-commit-config.yaml`:

<details><summary>file content</summary>

```bash
❯ cat .pre-commit-config.yaml
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.75.0
    hooks:
      - id: terraform_fmt
      - id: terraform_wrapper_module_for_each
      - id: terraform_validate
      - id: terraform_docs
        args:
          - '--args=--lockfile=false'
      - id: terraform_tflint
        args:
          - '--args=--only=terraform_deprecated_interpolation'
          - '--args=--only=terraform_deprecated_index'
          - '--args=--only=terraform_unused_declarations'
          - '--args=--only=terraform_comment_syntax'
          - '--args=--only=terraform_documented_outputs'
          - '--args=--only=terraform_documented_variables'
          - '--args=--only=terraform_typed_variables'
          - '--args=--only=terraform_module_pinned_source'
          - '--args=--only=terraform_naming_convention'
          - '--args=--only=terraform_required_version'
          - '--args=--only=terraform_required_providers'
          - '--args=--only=terraform_standard_module_structure'
          - '--args=--only=terraform_workspace_remote'
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
```

</details>
