### ISSUE TITLE
Terraform-docs behaving differently on different machines.

### ISSUE THREAD

**Issue by RiccardoGrigoletto** [antonbabenko/pre-commit-terraform#452]
### Terraform-docs behaving differently on different machines.

We use pre-commit-terraform in our project.
I run the terraform_docs hooker both from a docker container and MacOS.

When running pre-commit, MacOS wants to modify the documentation in the provider section:
```
-| <a name="provider_google"></a> [google](#provider\_google) | = 4.19.0 |
+| <a name="provider_google"></a> [google](#provider\_google) | 4.19.0 |
```

While in docker it is the opposite
```
-| <a name="provider_google"></a> [google](#provider\_google) | 4.19.0 |
+| <a name="provider_google"></a> [google](#provider\_google) | = 4.19.0 |
```

This doesn't happen in all the folders where I have a GCP project but only in some of them.

My hook is:
```
-   repo: https://github.com/antonbabenko/pre-commit-terraform
    rev:  v1.77.0 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
    hooks:
    -   id: terraform_docs
        args:
        - --hook-config=--create-file-if-not-exist=true
        - --hook-config=--path-to-file=TFDOC.md
```

The terraform provider is:

```
required_providers {
    google = {
      source  = "hashicorp/google"
      version = "= 4.19.0"
    }
    google-beta = {
      source  = "hashicorp/google-beta"
      version = "= 4.19.0"
    }
  }
```

### How can we reproduce it?
Run terraform pre-commit hook for terraform_docs in a Docker container and then in MacOS using google as provider.

### Environment information

OS: Docker container Win10 with Ubuntu 20.04 on WSL2
OS: MacOS

* Tools availability and versions:

```bash
GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)
pre-commit 2.15.0
Terraform v1.1.9
python SKIPPED
Python 3.8.10
checkov 2.0.888
terraform-docs version v0.16.0 1f686b1 linux/amd64
terragrunt version v0.37.1
terrascan terrascan SKIPPED
TFLint version 0.34.1
tfsec tfsec SKIPPED
tfupdate tfupdate SKIPPED
hcledit hcledit SKIPPED
```
MacOS:
```bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin22)
pre-commit 2.20.0
Terraform v1.1.9
python SKIPPED
Python 3.7.9
checkov 2.2.75
terraform-docs version v0.16.0 darwin/amd64
terragrunt SKIPPED
terrascan terrascan SKIPPED
TFLint version 0.39.3
tfsec tfsec SKIPPED
tfupdate tfupdate SKIPPED
hcledit hcledit SKIPPED
```
