### ISSUE TITLE
How to run pre-build docker image in Gitlab CI

### ISSUE THREAD

**Issue by ecoupal-believe** [antonbabenko/pre-commit-terraform#515]
For no reason sometimes my pipeline fails with this error:

![image](https://user-images.githubusercontent.com/103646557/235160738-ad947bcf-250f-452e-bb02-23ecd6cad02a.png)

Here is my .gitlab-ci.yaml:

![image](https://user-images.githubusercontent.com/103646557/235160966-b227407a-230a-49b9-8f84-d1a5c4629ce7.png)

Any idea why does this happens ?

**Comment by Agrendalath** [comment]
@ecoupal-believe, I'm running it like this in GitLab CI:
```yaml
validate:
  image:
    name: ghcr.io/antonbabenko/pre-commit-terraform
    entrypoint: [/bin/sh, -c]
  script: pre-commit run -a
```
