### ISSUE TITLE
[wrong configured WSL] pre-commit failing with "invalid option name" in WSL2

### ISSUE THREAD

**Issue by fabiogalera** [antonbabenko/pre-commit-terraform#516]
### Describe the bug

Running `pre-commit run --files *.tf *.md`, script is failing with error `: invalid option name`

Tried to run the scripts using bash, but without much success

```
galerfa@galera:~/.cache/pre-commit/repo_5ly5c51/hooks$ bash terraform_tflint.sh
terraform_tflint.sh: line 2: $'\r': command not found
: invalid option nameline 3: set: pipefail
galerfa@galera:~/.cache/pre-commit/repo_5ly5c51/hooks$ bash terragrunt_validate.sh
: invalid option nameh: line 2: set: pipefail
galerfa@galera:~/.cache/pre-commit/repo_5ly5c51/hooks$
````

### How can we reproduce it?

```bash
galerfa@galera:~/repos/infrastructure/vpc$ pre-commit run --files *.tf *.md
pre-commit run --files *.tf *.md
Terraform fmt............................................................Failed
- hook id: terraform_fmt
- exit code: 2

: invalid option namepre-commit/repo6f7es1d3/hooks/terraform_fmt.sh: line 2: set: pipefail
: invalid option namepre-commit/repo6f7es1d3/hooks/terraform_fmt.sh: line 2: set: pipefail

Terraform validate.......................................................Failed
- hook id: terraform_validate
- exit code: 2

: invalid option namepre-commit/repo6f7es1d3/hooks/terraform_validate.sh: line 2: set: pipefail

Terraform docs...........................................................Failed
- hook id: terraform_docs
- exit code: 2

: invalid option namepre-commit/repo6f7es1d3/hooks/terraform_docs.sh: line 2: set: pipefail

check for merge conflicts................................................Passed
fix end of files.........................................................Passed
detect aws credentials...................................................Passed
detect private key.......................................................Passed
check for case conflicts.................................................Passed
```

### Environment information

OS: Win10 with Ubuntu 20.04 on WSL2

```bash
uname -a
Linux galera 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

* Tools availability and versions:

```
GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)
pre-commit 2.20.0
Terraform v1.3.2
python SKIPPED
Python 3.8.10
checkov checkov SKIPPED
terraform-docs version v0.16.0 1f686b1 linux/amd64
terragrunt version v0.45.4
terrascan terrascan SKIPPED
TFLint version 0.46.1
+ ruleset.terraform (0.2.2-bundled)
tfsec tfsec SKIPPED
tfupdate tfupdate SKIPPED
hcledit hcledit SKIPPED
```

* `.pre-commit-config.yaml`:

<details><summary>file content</summary>

```
repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.77.3
  hooks:
    - id: terraform_fmt
    - id: terraform_validate
    - id: terraform_docs
      args:
          - --args=--html=true --anchor=true
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
    - id: check-merge-conflict
    - id: end-of-file-fixer
    - id: detect-aws-credentials
      args:
        - --allow-missing-credentials
    - id: detect-private-key
    - id: check-case-conflict
```

</details>
