### ISSUE TITLE
Support tflint modules with differing module dependencies

### ISSUE THREAD

**Issue by davidjb** [antonbabenko/pre-commit-terraform#534]
### What problem are you facing?

In my configuration, I have a number of different modules in the same repo but each module has differing dependencies (either local or published). At present, I'm linting by running `cd {dir} && terraform get && tflint` for each module directory to ensure all dependencies are available and installed. When trying to use the `terraform_tflint` hook, it fails for modules with dependencies.

### How could pre-commit-terraform help solve your problem?

Have the ability to automatically invoke `terraform get` per-directory when running the `tflint` hook, either by default or with a flag. Whilst `terraform get` is a noop when nothing needs to be done, it still takes time to be invoked so an opt-in hook flag may be the better option.

Happy to help craft a PR if this is something that could be incorporated.

**Comment by MaxymVlasov** [comment]
You can do next as a workaround (because `t init` took more time than `t get`)

```yaml
- id: terraform_validate
  args:
    - --hook-config=--retry-once-with-cleanup=true
    # - --tf-init-args=-upgrade
- id: terraform_tflint
  args:
    - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
```

Also, because tflint and validate can't fully replace each other, it can be solution, not a temporary workaround
