### ISSUE TITLE
terraform_docs hook not detecting changed files in subdirectories

### ISSUE THREAD

**Issue by dgarlitt** [antonbabenko/pre-commit-terraform#559]
### To reproduce

Create the following directory structure:

```yaml
/ # Project Root
|_ .config/
      |_ footer.md
      |_ header.md
      |_ .terraform-docs.yml
|_ .pre-commit-config.yaml
|_ README.md
|_ main.tf
|_ outputs.tf
|_ variables.tf
```

<details><summary>.config/footer.md</summary>

```md

## This is a footer

```

</details>

---

<details><summary>.config/fheader.md</summary>

```md

## This is a header

```

</details>

---

<details><summary>.config/.terraform-docs.yml</summary>

```yaml
formatter: "markdown" # this is required

version: ""

header-from: .config/header.md
footer-from: .config/footer.md

recursive:
  enabled: false
  path: modules

sections:
  hide: []
  show: []

content: ""

output:
  file: "README.md"
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: false
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true

```

</details>

---

<details><summary>.pre-commit-config.yaml</summary>

```yaml
default_install_hook_types: [pre-commit, pre-push, commit-msg]
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.82.0
    hooks:
      - id: terraform_docs
        files: '.*$'

```

<br />notice the `files` field regex is set to pick up any file changes.

</details>

---

<details><summary>README.md</summary>

```md
# My Project

<!-- BEGIN_TF_DOCS -->

## This is a header

## Requirements

No requirements.

## Providers

No providers.

## Modules

No modules.

## Resources

No resources.

## Inputs

No inputs.

## Outputs

No outputs.

## This is a footer
<!-- END_TF_DOCS -->

```

</details>

---

<details><summary>main.tf</summary>

```bash
# Empty
```

</details>

---

<details><summary>outputs.tf</summary>

```bash
# Empty
```

</details>

---

<details><summary>variables.tf</summary>

```bash
# Empty
```

</details>

---

With all of these files committed, do the following:
 - run `pre-commit install`
 - make a change to the `header.md` file in the `.config` directory
 - stage the change for commit: `git add .config`
 - run `pre-commit run terraform_docs` or `git commit -m "change to the header"`

You will see the following:
```bash
$ pre-commit run terraform_docs
Terraform docs...........................................................Passed
```
and the `README.md` is unchanged even though the `.config/header.md` file was changed:

```bash
$ git status
On branch main
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        modified:   .config/header.md
```

Now run with `--all-files` to get the expected output:

```bash
$ pre-commit run terraform_docs --all-files
Terraform docs...........................................................Failed
- hook id: terraform_docs
- files were modified by this hook
```

```bash
$ git status
On branch main
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        modified:   .config/header.md

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   README.md
```

However, if you move the `header.md` and/or `footer.md` into the project root and update the `.config/terraform-docs.yml` `header-from` and/or `footer-from` fields accordingly, any changes to these files are detected.

### Environment information

* OS:  MacOS

* `uname -a` and/or `systeminfo | Select-String "^OS"` output:

```bash
Darwin ip-192-168-0-107.us-west-2.compute.internal 22.5.0 Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:22 PDT 2023; root:xnu-8796.121.3~7/RELEASE_X86_64 x86_64
```

* Tools availability and versions:

```bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin22)
pre-commit 3.3.3
Terraform v1.4.6
python SKIPPED
Python 3.11.4
checkov checkov SKIPPED
terraform-docs version v0.16.0 darwin/amd64
terragrunt version v0.45.11
terrascan terrascan SKIPPED
TFLint version 0.35.0
tfsec v1.19.1
tfupdate 0.7.2
hcledit bash: line 13: hcledit: command not found

```

* `.pre-commit-config.yaml`: (see above)
