### ISSUE TITLE
terraform_tfsec hook always runs on all files

### ISSUE THREAD

**Issue by devholland** [antonbabenko/pre-commit-terraform#569]
### Describe the bug
The `terraform_tfsec` hook always runs on all Terraform files, even though none of them were modified or staged.

I would expect the hook to only run if I explicitly use `pre-commit run --all-files` or if there were any Terraform files modified and staged.

### How can we reproduce it?
What I did to produce the bug:
```
$ touch test.py
$ git add test.py
$ pre-commit run
```

My `.pre-commit-config.yaml` contains:
```
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.83.2
    hooks:
      - id: terraform_tfsec
```

### Environment information

* OS: Ubuntu 22.04

* `uname -a` and/or `systeminfo | Select-String "^OS"` output:

```bash
Linux Yggdrasil 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

* Tools availability and versions:

```bash
pre-commit 3.4.0
```

* `.pre-commit-config.yaml`:

<details><summary>file content</summary>

```bash
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.83.2
    hooks:
      - id: terraform_tfsec
```

</details>
