### ISSUE TITLE
No such file or directory on hooks files, seems like the \ are removed for path.

### ISSUE THREAD

**Issue by LvffY** [antonbabenko/pre-commit-terraform#574]
### Describe the bug

In our terraform repositories, we try to use your pre-commit hooks. It seems like there is an issue on Windows which removes all the `\` from paths that makes the paths not existing. 

If you look at the exact same paths (just with `\`) the **.sh** files exist.

Also, if we use another hook for **terraform-docs** for example, on is successful while the other failed.

For example with this **.pre-commit-config.yaml**

```yaml
repos:
  - repo: https://github.com/terraform-docs/terraform-docs
    rev: "v0.16.0"
    hooks:
      - id: terraform-docs-go
        args: ["markdown", "table", "--output-file", "README.md", "./"]
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: "v1.74.1"
    hooks:
      - id: terraform_fmt
```

### How can we reproduce it?

Run `pre-commit run -a` on a windows workstation.

### Environment information

* OS:  Windows 11

* `uname -a` and/or `systeminfo | Select-String "^OS"` output:

```bash
Microsoft Windows 11 Entreprise
```

* Tools availability and versions:

![image](https://github.com/antonbabenko/pre-commit-terraform/assets/37327656/07c3e534-29c5-4554-9527-8f29a83cf1fe)

* `.pre-commit-config.yaml`:

<details><summary>file content</summary>

```yaml

repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.81.0 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
  hooks:
    - id: terraform_fmt
    - id: terraform_docs
```

</details>
