### ISSUE TITLE
"tfupdate provider" to upgrade to latest minor version instead of major version.

### ISSUE THREAD

**Issue by rd-michel** [antonbabenko/pre-commit-terraform#583]
### What problem are you facing?

I would like to use

`tfupdate provider <providername>` to upgrade to the latest **minor** version of a provider. current behavior is that "tfupdate provider" will upgrade to the latest version even when this is a major upgrade (with possible breaking changes).

### How could pre-commit-terraform help solve your problem?

Would be nice if the pre-commit hook implements some kind of version constraint,

Example mockup code:
```
- id: tfupdate
        name: Autoupdate google provider version
        args:
          - --constraint="version<4.0.0"
          - --args=provider google
```

so that tfupdate command would upgrade to latest 3.X.X version but not to google provider version 4.X.X

**Comment by yermulnik** [comment]
I'm not quite sure I understood the description of desired problem resolution, though I'd like to admit that `pre-commit-terraform` is a thin wrapper for `tfupdate` among other tools and it doesn't provide any extended functionality that is not provided by the tool itself.
You actually can pass any args supported by `tfupdate` to the hook: https://github.com/antonbabenko/pre-commit-terraform#tfupdate
What you probably are looking for is `-v  --version      A new version constraint (default: latest)`: https://github.com/minamijoyo/tfupdate#provider

**Comment by rd-michel** [comment]
Thanks @yermulnik 

after a discussion with the author of tfupdate and some testen i found the right solution

here is an example of a terraform version update and a provide update (in the existing terraform code) ... without accidently upgrading to the next major update.

```
      - id: tfupdate
        name: Autoupdate Terraform version
        args:
          - --args=terraform
          - --args=--version="~> 1.6"
      - id: tfupdate
        name: Autoupdate google provider version
        args:
          - --args=provider google
          - --args=--version="~> 5"
```
