### ISSUE TITLE
[terraform_docs] Specify max-depth to replicate terraform-docs behavior

### ISSUE THREAD

**Issue by oliveirafilipe** [antonbabenko/pre-commit-terraform#616]
### What problem are you facing?
The current behavior of the `terraform_docs` hook is to iterate over all files when `pre-commit --all-files` command is run. This is a good thing when you want to apply the hooks over all files, for example, `terraform_tflint` hook. 
Unfortunately, the `--all-files` flag when using `terraform_docs` hook causes the hook to generate files for every subfolder, when `--hook-config=--create-file-if-not-exist=true`.

```
$ tree
.
└── modules
    ├── bar
    │   ├── example
    │   │   └── main.tf
    │   └── main.tf
    └── foo
        ├── example
        │   └── main.tf
        └── main.tf

6 directories, 4 files

$ pre-commit run --all-files --verbose
Terraform docs...........................................................Passed
- hook id: terraform_docs
- duration: 0.84s

$ tree
.
└── modules
    ├── bar
    │   ├── README.md
    │   ├── example
    │   │   ├── README.md
    │   │   └── main.tf
    │   └── main.tf
    └── foo
        ├── README.md
        ├── example
        │   ├── README.md
        │   └── main.tf
        └── main.tf

6 directories, 8 files
```
This is not the current behavior of `terraform-docs` cli, even when `recursive` is enabled, it will only read for 1 level below the specified `recursive.path`. [terraform-docs/internal/cli/run.go#L259](https://github.com/terraform-docs/terraform-docs/blob/7843ec208ed67aa51ffacabd47ed940388e8b7aa/internal/cli/run.go#L259)

```
$ tree
.
└── modules
    ├── bar
    │   ├── example
    │   │   └── main.tf
    │   └── main.tf
    └── foo
        ├── example
        │   └── main.tf
        └── main.tf

6 directories, 4 files

$ terraform-docs .
README.md updated successfully
modules/bar/README.md updated successfully
modules/foo/README.md updated successfully
 
$ tree
.
├── README.md
└── modules
    ├── bar
    │   ├── README.md
    │   ├── example
    │   │   └── main.tf
    │   └── main.tf
    └── foo
        ├── README.md
        ├── example
        │   └── main.tf
        └── main.tf

6 directories, 7 files
```
My need is:
* Keep running all hooks in pre-commit for all files (`pre-commit --all-files`) but only create documents using `terraform_docs` hook for the root folder of each module inside `modules/` folder

### How could pre-commit-terraform help solve your problem?
`terraform_docs` could have a `max-depth` configuration attribute that will restrict document generation for N or fewer levels below the current folder

```yml
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.86.0
    hooks:
      - id: terraform_docs
        args:
          - --hook-config=--create-file-if-not-exist=true
          - --hook-config=--max-depth=2
      - id: terraform_tflint
```

**Comment by yermulnik** [comment]
> but only create documents using terraform_docs hook for the root folder of each module inside `modules/` folder

FYI: `--hook-config=--max-depth=2` — the `--hook-config` handles hook-specific parameters. For the tfdocs-specific parameters you want `--args=--max-depth=2`

Given you mean each 1st level dir inside `modules/`, you would want to limit which files `pre-commit` triggers tfdocs hook for by adding something like `files: ^modules/[^/]+/[^/]+\.(tf|terraform\.lock\.hcl)$` to tfdocs configuration block in `.pre-commit-hooks.yaml` file:
```yaml
- id: terraform_docs
  name: Terraform docs
  description: Inserts input and output documentation into README.md (using terraform-docs).
  require_serial: true
  entry: hooks/terraform_docs.sh
  language: script
  files: ^modules/[^/]+/[^/]+\.(tf|terraform\.lock\.hcl)$
  exclude: \.terraform\/.*$
```

Please let me know if this works for your use case.

**Comment by MaxymVlasov** [comment]
`--hook-config=--max-depth` is not supported in `terraform_docs`

But `--args=--max-depth=2` should works fine

**Comment by oliveirafilipe** [comment]
Hi folks, thank you for your quick response. 

@yermulnik Thank you for the suggestion, it worked, only the files in the 1st level of the module's folder were selected.

```yml
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.86.0
    hooks:
      - id: terraform_docs
        files: ^modules/[^/]+/[^/]+\.(tf|terraform\.lock\.hcl)$
        args:
            ...
```

For clarification, also answering @MaxymVlasov, when I created this issue it was a feature request, that's why I suggested a new parameter `--hook-config=--max-depth`, there's no `max-depth` argument for tf-docs.

But since the `files` attribute in `.pre-commit-config.yaml` worked, I think we can close it.
