### ISSUE TITLE
Add PATH to terraform_docs

### ISSUE THREAD

**Issue by carim-w** [antonbabenko/pre-commit-terraform#668]
### What problem are you facing?

I have a repository with 100 **independent** terraform modules inside.
Each module has inside this `.terraform-docs.yml`:
```
formatter: "markdown"
header-from: main.tf
output:
  file: "README.md"
  mode: inject
```

Right now, I'm running this script to generate documentation (it's working):

```
terraform-docs blueprints/aws/eks
terraform-docs blueprints/aws/vpc
terraform-docs blueprints/gpc/gke
... 100 more lines ...
```

But I want to use your `pre-commit-config` instead of my script.

I can't achieve that using the **terraform_docs**. There's no option to use PATH, like the official terraform-docs module: https://terraform-docs.io/how-to/pre-commit-hooks/

### How could pre-commit-terraform help solve your problem?

Implement the PATH option, or, if it already exists it's not clear in the documentation ow to use it.

Would be useful something like this:

```
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.89.1
    hooks:
      - id: terraform_docs
        args: 
        - blueprints/gpc/gke
      - id: terraform_docs
        args: 
        - blueprints/aws/eks
```

Or even better:
```
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.89.1
    hooks:
      - id: terraform_docs
        args: 
        - paths: 
          - blueprints/gpc/gke
          - blueprints/aws/eks
```

**Comment by yermulnik** [comment]
> I can't achieve that using the **terraform_docs**.

Can you please elaborate on the issue?
By default `terraform_docs` hook is run inside each directory with changed TF files.

**Comment by yermulnik** [comment]
Please also beware that `terraform_docs` hook differs from running pure `terraform-docs` tool: https://github.com/antonbabenko/pre-commit-terraform#terraform_docs

**Comment by carim-w** [comment]
> > I can't achieve that using the **terraform_docs**.
> 
> Can you please elaborate on the issue? By default `terraform_docs` hook is run inside each directory with changed TF files.

Yes, my question is very simple:
What is the way using `terraform_docs` to do the same that my script does?

My script generates a `README.md` file inside each module directory.

So, How can I specify the PATH in your `terraform_docs` wrapper?

```
$ terraform-docs 
A utility to generate documentation from Terraform modules in various output formats

Usage:
  terraform-docs [PATH] [flags]  <----- this PATH I want to pass
```

**Comment by yermulnik** [comment]
I feel like you're misinterpreting a bit what `pre-commit` is for, though to achieve your goal you may try the below hook config:
```yaml
- id: terraform_docs
  always_run: true
  args:
    - __GIT_WORKING_DIR__/blueprints/aws/eks
```
If this works and does what you expect it to, then you'll have to create this for each and every directory you want this hook to be run in on each commit.
As in not just add `args` but replicate the whole hook block for each dir:
```yaml
- id: terraform_docs
  always_run: true
  args:
    - __GIT_WORKING_DIR__/blueprints/aws/eks

- id: terraform_docs
  always_run: true
  args:
    - __GIT_WORKING_DIR__/blueprints/aws/vpc

[so on]
```

**Comment by carim-w** [comment]
Exactly, it doesn't work. I'll copy the full file here.
```
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.89.1
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
        always_run: true
        args:
        - __GIT_WORKING_DIR__/blueprints/aws/eks
```
Then, If I run: 
```
git add .
pre-commit
```
Output:
```
Terraform fmt............................................................Passed  
Terraform docs...........................................................Passed
```

`terraform_fmt` works perfectly (in case I have files to modified)
Instead, `terraform_docs` do nothing. Not even an error in the output.

But if I run a simple command in CLI:
`terraform-docs blueprints/aws/eks`
Output:
`blueprints/aws/eks/README.md updated successfully`

**Comment by MaxymVlasov** [comment]
```yaml
- id: terraform_docs
  args:
    - --args=--config=.terraform-docs.yml
    - --hook-config=--create-file-if-not-exist=true # Boolean. true or false
    - --hook-config=--use-standard-markers=true     # Boolean. Defaults in v1.x to false. Set to true for compatibility with terraform-docs
 ```
 
 + run via `pre-commit run -a` to init them for first time
