### ISSUE TITLE
terraform_docs hook fails to detect out-of-date document

### ISSUE THREAD

**Issue by vchepkov** [antonbabenko/pre-commit-terraform#692]
### Describe the bug

When using the following configuration, terraform_docs hook doesn't fail as expected

```
repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform.git
  rev: v1.92.0
  hooks:
    - id: terraform_docs
      args:
        - --args=--lockfile=false
        - --args=--output-check=true
        - --hook-config=--use_standard_markers=true
```

Where as standalone command does:
```
$ terraform-docs markdown --lockfile=false --output-check=true --output-file README.md .
Error: README.md is out of date
```
### How can we reproduce it?

Update README.md to make it out of date and re-run pre-commit run -a

### Environment information
* OS:  macOS
