### ISSUE TITLE
Trivy is not sandboxed 

### ISSUE THREAD

**Issue by TiansuYu** [antonbabenko/pre-commit-terraform#696]
When I run pre-commit hooks with 
```yaml
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.92.1
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_trivy
        files: infra/
```

Then the hook `terraform_trivy` will complain `/Users/xxxx/.cache/pre-commit/repo30dyuizv/hooks/terraform_trivy.sh: line 51: trivy: command not found`. 

This can be fixed by additionally installing trivy via brew. That means trivy is not included into the sandbox environment controlled by pre-commit hook.
