### ISSUE TITLE
Config output.file is ignored

### ISSUE THREAD

**Issue by drAlberT** [antonbabenko/pre-commit-terraform#710]
### Describe the bug

Removing the `--hook-config=--path-to-file` option in the hook configuration makes the hook to create a "default" file named "README.md", even if an "output.file" property is present in the configuration file.

If, on the other hand, it is present then it is used despite the value of the config file.

### How can we reproduce it?

<details><summary>hook configuration</summary>

```yaml
- repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.94.1
    hooks:
      - id: terraform_docs
        args:
          - --hook-config=--add-to-existing-file=false
          - --hook-config=--create-file-if-not-exist=true
          - --hook-config=--parallelism-ci-cpu-cores=1
          - --hook-config=--path-to-file=MODULE-DETAILS.md
```
</details>
<details><summary>terraform-doc configuration</summary>

```yaml
---

formatter: markdown

output:
  mode: replace
  file: MODULE-DETAILS.md
  template: |-
    <!-- BEGIN_TF_DOCS -->
    # Module details

    {{ .Content }}
    <!-- END_TF_DOCS -->

settings:
  anchor: false
  hide-empty: true
  html: false
  lockfile: false
```
</details>

### Environment information

* OS:  

* `uname -a` and/or `systeminfo | Select-String "^OS"` output:

```bash
uname -v
Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:30 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T6000
```

* Tools availability and versions:

```bash
bash << EOF
bash --version | head -n 1                2>/dev/null || echo "bash SKIPPED"
pre-commit --version                      2>/dev/null || echo "pre-commit SKIPPED"
tofu --version | head -n 1                2>/dev/null || echo "opentofu SKIPPED"
terraform --version | head -n 1           2>/dev/null || echo "terraform SKIPPED"
python --version                          2>/dev/null || echo "python SKIPPED"
python3 --version                         2>/dev/null || echo "python3 SKIPPED"
echo -n "checkov " && checkov --version   2>/dev/null || echo "SKIPPED"
infracost --version                       2>/dev/null || echo "infracost SKIPPED"
terraform-docs --version                  2>/dev/null || echo "terraform-docs SKIPPED"
terragrunt --version                      2>/dev/null || echo "terragrunt SKIPPED"
echo -n "terrascan " && terrascan version 2>/dev/null || echo "SKIPPED"
tflint --version                          2>/dev/null || echo "tflint SKIPPED"
echo -n "tfsec " && tfsec --version       2>/dev/null || echo "SKIPPED"
echo -n "trivy " && trivy --version       2>/dev/null || echo "SKIPPED"
echo -n "tfupdate " && tfupdate --version 2>/dev/null || echo "SKIPPED"
echo -n "hcledit " && hcledit version     2>/dev/null || echo "SKIPPED"
EOF
GNU bash, version 5.2.32(1)-release (aarch64-apple-darwin23.4.0)
pre-commit 3.8.0
bash: line 3: tofu: command not found
Terraform v1.5.7
python SKIPPED
Python 3.12.5
checkov 3.2.2
infracost SKIPPED
terraform-docs version v0.18.0 darwin/arm64
terragrunt version 0.67.1
terrascan version: v1.19.1
TFLint version 0.53.0
+ ruleset.terraform (0.9.1-bundled)
tfsec v1.28.10
trivy Version: 0.54.1
Check Bundle:
  Digest: sha256:ef2d9ad4fce0f933b20a662004d7e55bf200987c180e7f2cd531af631f408bb3
  DownloadedAt: 2024-06-27 15:35:31.210038 +0000 UTC
tfupdate 0.8.5
hcledit SKIPPED
```

![Screenshot 2024-09-02 at 11 23 10](https://github.com/user-attachments/assets/11731954-4861-41ee-8f86-2c74bd214677)
![Screenshot 2024-09-02 at 11 23 21](https://github.com/user-attachments/assets/bb000552-7e99-46db-94f9-7adca79864b5)
![Screenshot 2024-09-02 at 11 23 34](https://github.com/user-attachments/assets/cbcab307-5df8-4e81-989b-ad4ec17f6046)

**Comment by MaxymVlasov** [comment]
You didn't specify config file
https://github.com/antonbabenko/pre-commit-terraform?tab=readme-ov-file#terraform_docs p.4

**Comment by drAlberT** [comment]
> Btw, when you use `mode: replace` you can avoid
> 
> ```yaml
> 
> 
> 
> ```
> 
> as entire file will be replaced in any case

@MaxymVlasov I was avoiding it, it's what I expect in fact .. but starting from last release I had to add it otherwise I get errors ;(

**Comment by MaxymVlasov** [comment]
What errors?

**Comment by drAlberT** [comment]
> You didn't specify config file https://github.com/antonbabenko/pre-commit-terraform?tab=readme-ov-file#terraform_docs p.4

It is correctly using the template block included in the default config file, so I guess there is no need to explicely pass the name of the config file if I'm not using a non-standard name for it ...

**Comment by MaxymVlasov** [comment]
You mostly never run `terraform-docs` from repo root when you pre-commit hooks, so specification of config location is required

**Comment by drAlberT** [comment]
> What errors?

This is my "original configuration" that was pèerfectly working before latest release:
![Screenshot 2024-09-02 at 15 35 34](https://github.com/user-attachments/assets/0cc60a9c-c01a-44bc-9281-c0d475110325)

But with this config, now, I get the following error (and similar for end marker):
![Screenshot 2024-09-02 at 15 36 28](https://github.com/user-attachments/assets/77b46ee6-d523-4f1f-bee8-a0b1b0157726)

To have it work again I had to change as follow (note the use of `|-` operator too, otherwise the end-of marker is not recognised):
![Screenshot 2024-09-02 at 15 35 45](https://github.com/user-attachments/assets/45dab795-b79c-43ae-afaa-95b02ffb5f95)

I also had to change my `.editorconfig` file to allow the lack of EOL in the generated file.

**Comment by MaxymVlasov** [comment]
This is work for me (get it from one of prev issues)

```yaml
formatter: "md"

output:
  mode: replace
  template: |-
        {{ .Content }}
  file: tfdocs.md
```


```yaml
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.94.1
    hooks:
      - id: terraform_docs
        args:
          - --args=--config=.terraform-docs.yml
          - --hook-config=--create-file-if-not-exist=true
```

**Comment by drAlberT** [comment]
You were right, my issue was the lack of config-file specification. Now it works perfectly with the following configurations:

![Screenshot 2024-09-02 at 15 47 29](https://github.com/user-attachments/assets/39d27e70-e2fc-4ed3-adf9-d880c6d1eb1d)
![Screenshot 2024-09-02 at 15 47 39](https://github.com/user-attachments/assets/9a7bd7de-bd30-447c-89f2-8a8f6af08b81)


**Thank you very much for your support!**

(I still don't understand why the content of the template was used ... maybe you could make it a bit more clear in the documentation that it is mandatory to specify the config file in such cases :) )

**Comment by MaxymVlasov** [comment]
this work for me too
```yaml
formatter: markdown

output:
  mode: replace
  template: |
        {{ .Content }}

  file: tfdocs.md
```
