### ISSUE TITLE
tflint - No such file or directory 

### ISSUE THREAD

**Issue by vitali-shcharbin** [antonbabenko/pre-commit-terraform#80]
Hello, for my typical terraform + terragrunt repo with following .tflint.hcl configuration:
```
config {
  module     = true
  deep_check = false
  force      = false
}
```

And following hook configuration:
```
  - repo: git://github.com/antonbabenko/pre-commit-terraform
    rev: v1.21.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_tflint
        args: [' --config .tflint.hcl']
      - id: terragrunt_fmt
```

Getting following errors:
```
/Users/user/.cache/pre-commit/repo31phc1no/terraform_tflint.sh: line 42: pushd --config .tflint.hcl modules/dynamodb-table/dynamodb-table.tf modules/dynamodb-table/dynamodb-table-outputs.tf modules/s3-state-bucket: No such file or directory
```
