### ISSUE TITLE
Terraform docs - Error: accepts 1 arg(s), received 2

### ISSUE THREAD

**Issue by millouzgc** [antonbabenko/pre-commit-terraform#802]
### Describe the bug

- v1.97.2 => Error
- v1.97.1 => OK

```
Terraform docs...........................................................Failed
- hook id: terraform_docs
- duration: 0.04s
- exit code: 1

Error: accepts 1 arg(s), received 2
```

### Environment information

* OS:  
```bash
Linux 4.18.0-553.33.1.el8_10.x86_64 #1 SMP Fri Dec 6 15:07:20 EST 2024 x86_64 x86_64 x86_64 GNU/Linux
```
* Tools availability and versions:

```bash
GNU bash, version 4.4.20(1)-release (x86_64-redhat-linux-gnu)
pre-commit 3.3.3
Terraform v1.8.1
python SKIPPED
Python 3.6.8
checkov 2.3.38
infracost SKIPPED
terraform-docs version v0.16.0 1f686b1 linux/amd64
terragrunt SKIPPED
terrascan SKIPPED
tflint SKIPPED
tfsec SKIPPED
trivy SKIPPED
tfupdate SKIPPED
hcledit SKIPPED
```

* `.pre-commit-config.yaml`:

<details><summary>file content</summary>

```yaml
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.97.2
  hooks:
  - id: terraform_docs
  - id: terraform_fmt
  - id: terraform_validate
  - id: terraform_checkov
    args:
      - --args=--quiet
      - --args=--download-external-modules true
```

</details>
