### ISSUE TITLE
The terraform-docs hook no longer generated since the pre-commit-terraform v1.94.3

### ISSUE THREAD

**Issue by acelebanski** [antonbabenko/pre-commit-terraform#807]
### Describe the bug

I thought I have the same bug as described in issue #721 but it got resolved and my problem still persists. My pre-commit hook doesn't generate README files since version `v1.94.3`, so the last working version for me is `v1.94.2`.

### How can we reproduce it?

Files contents with links to the repo pasted below.

### Environment information

* OS:  macOS 15.2 (24C101)

* `uname -a` and/or `systeminfo | Select-String "^OS"` output:

```bash
Darwin M-M4676TH5QP 24.2.0 Darwin Kernel Version 24.2.0: Fri Dec  6 19:01:59 PST 2024; root:xnu-11215.61.5~2/RELEASE_ARM64_T6000 arm64
```

* Tools availability and versions:

```bash
GNU bash, version 3.2.57(1)-release (arm64-apple-darwin24)
pre-commit 4.0.1
bash: line 3: tofu: command not found
Terraform v1.8.5
Python 3.11.10
Python 3.11.10
checkov 3.2.345
Infracost v0.10.40
terraform-docs version v0.19.0 darwin/arm64
terragrunt SKIPPED
terrascan version: v1.19.9
TFLint version 0.54.0
+ ruleset.terraform (0.10.0-bundled)
tfsec v1.28.12
trivy SKIPPED
tfupdate 0.8.5
hcledit 0.2.15
```

* [.pre-commit-config.yaml](https://github.com/PaloAltoNetworks/terraform-azurerm-swfw-modules/blob/main/.pre-commit-config.yaml):

<details><summary>file content</summary>

```yaml
  - args:
    - --args=--config=.terraform-docs.yml
    id: terraform_docs
```
</details>

* [.terraform-docs.yml](https://github.com/PaloAltoNetworks/terraform-azurerm-swfw-modules/blob/main/.terraform-docs.yml):

<details><summary>file content</summary>

```yaml
formatter: "markdown document" # this is required
version: ""
header-from: ".header.md"

output:
  file: README.md
  mode: replace
  template: |-
    {{ .Content }}

sort:
  enabled: false

settings:
  indent: 3
  lockfile: false
  escape: false

content: |-
(...)
```
</details>
