### ISSUE TITLE
Unexpected `tofu` invocation in `terraform`-only project

### ISSUE THREAD

**Issue by wyardley** [antonbabenko/pre-commit-terraform#817]
### Describe the bug
In versions after `1.89.1`, I seem to get an error with tofu not being in my path. In this particular setup, I'm using terraform only, and not OpenTofu:

```
Terraform fmt............................................................Failed
- hook id: terraform_fmt
- exit code: 127

/Users/xxx/.cache/pre-commit/repoxyo8nzqd/hooks/terraform_fmt.sh: line 52: tofu: command not found
```
I'd rather not hard-code `tf_path` (though testing it, that didn't seem to help either).

```
% which terraform
/opt/homebrew/bin/terraform
% which tofu
tofu not found
```
### Environment information

* OS:  
OS: MacOS

* `uname -a` and/or `systeminfo | Select-String "^OS"` output:

```bash
Darwin xxxx 24.3.0 Darwin Kernel Version 24.3.0: Thu Jan  2 20:24:24 PST 2025; root:xnu-11215.81.4~3/RELEASE_ARM64_T6030 arm64
```

* Tools availability and versions:

```bash
GNU bash, version 3.2.57(1)-release (arm64-apple-darwin24)
pre-commit 4.1.0
bash: line 3: tofu: command not found
Terraform v1.10.5
python SKIPPED
Python 3.13.1
checkov SKIPPED
infracost SKIPPED
terraform-docs version v0.19.0 darwin/arm64
terragrunt SKIPPED
terrascan SKIPPED
TFLint version 0.55.1
+ ruleset.terraform (0.10.0-bundled)
tfsec SKIPPED
trivy SKIPPED
tfupdate SKIPPED
hcledit SKIPPED
```

* `.pre-commit-config.yaml`:

<details><summary>file content</summary>

```yaml
repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  # Latest still has some issues with it not finding the terraform binary, so
  # pin here for now.
  rev: v1.97.3
  tf_path: terraform
  hooks:
    - id: terraform_fmt
    - id: terraform_tflint
    - id: terraform_validate
      args:
        - --hook-config=--retry-once-with-cleanup=true
```

</details>

**Comment by MaxymVlasov** [comment]
Double-check that you have no any mentions to tofu anywhere, as 
```
/Users/xxx/.cache/pre-commit/repoxyo8nzqd/hooks/terraform_fmt.sh: line 52: tofu: command not found
```
https://github.com/antonbabenko/pre-commit-terraform/blob/1e54f11bfc5e3fd60ebd25d752c8dacafcb86cd2/hooks/terraform_fmt.sh#L51-L52

Means that you somehow were able to select "tofu" option

https://github.com/antonbabenko/pre-commit-terraform/blob/1e54f11bfc5e3fd60ebd25d752c8dacafcb86cd2/hooks/_common.sh#L462-L512

Please run `PCT_LOG=trace pre-commit run -a` wich next config ad post logs here

```yaml
repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.97.3
  hooks:
    - id: terraform_fmt
```


---

P.S. I surprised that this works at all, as `pre-commit` should fail when unknown options provided

```yaml
repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.97.3
  tf_path: terraform
  hooks:
    - id: terraform_fmt
```

`tf_path` do nothing here. Not sure how you end in this config, as in README it specified in [different way](https://github.com/antonbabenko/pre-commit-terraform?tab=readme-ov-file#11-custom-terraform-binaries-and-opentofu-support), so right setup will be next:

```yaml
repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.97.3
  hooks:
    - id: terraform_fmt
      args:
        - --hook-config=--tf-path=terraform
```

But it is redundant. I bet that there are something wrong with your local machine setup
