### ISSUE TITLE
[GHA] `tj-actions/changed-files` action is removed from GH

### ISSUE THREAD

**Issue by yermulnik** [antonbabenko/pre-commit-terraform#837]
Ref: https://www.stepsecurity.io/blog/harden-runner-detection-tj-actions-changed-files-action-is-compromised
> The tj-actions/changed-files GitHub Action, which is currently used in over 23,000 repositories, has been compromised. In this attack, the attackers modified the action’s code and retroactively updated multiple version tags to reference the malicious commit. The compromised Action prints CI/CD secrets in GitHub Actions build logs. If the workflow logs are publicly accessible (such as in public repositories), anyone could potentially read these logs and obtain exposed secrets.

Given we pin to commit'ish, we should be safe, but the `tj-actions/changed-files` repo has been disabled by GitHub, which means the GHA workflow `.github/workflows/build-image-test.yaml` should be failing now on that action step, which impacts the Docker Image build/test workflow.

**Comment by yermulnik** [comment]
Cc @MaxymVlasov

**Comment by MaxymVlasov** [comment]
Yep, our pinned commit is OK, as far as I see.

Need to find a fork and repoint it (if GH does not remove the whole git tree and all forks at once)

Or just start use a different action, there plenty of GHA with `changed-files` in name.

Will look into it next week

**Comment by MaxymVlasov** [comment]
Forks: https://web.archive.org/web/20241208095251/https://github.com/tj-actions/changed-files/forks

We can try https://github.com/zendesk/changed-files, as it contains most fresh data (Updated December 8, 2024 08:04)

**Comment by MaxymVlasov** [comment]
Another alternative from https://t.me/catops_chat/300466

```yaml
jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      changed-modules-total: ${{ steps.releases.outputs.matrix-length }}
      changed-modules: ${{ steps.releases.outputs.matrix }}
    steps:
      - name: "generate matrix | releases"
        id: releases
        uses: hellofresh/action-changed-files@v3
        with:
          pattern: "^(?!\\.github/)(?P<module>[^/]+)/"
```
