### ISSUE TITLE
Unable to use terraform_trivy

### ISSUE THREAD

**Issue by n-joergbode** [antonbabenko/pre-commit-terraform#838]
### Describe the bug
I just installed trivy on my local system and want to use the terraform_trivy plugin. Even the simplest configuration is not able to work.

### How can we reproduce it?

Write the following .-pre-commit-config.yaml

```yaml
repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.97.4 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
  hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_trivy
```

### Environment information

* OS:  Debian testing (trixie

* Tools availability and versions:
GNU bash, Version 5.2.37(1)-release (x86_64-pc-linux-gnu)
pre-commit 4.1.0
bash: Zeile 3: tofu: Kommando nicht gefunden.
Terraform v1.11.1
Python 3.13.2
Python 3.13.2
checkov SKIPPED
infracost SKIPPED
terraform-docs SKIPPED
terragrunt SKIPPED
terrascan SKIPPED
tflint SKIPPED
tfsec SKIPPED
trivy Version: 0.18.3
tfupdate SKIPPED
hcledit SKIPPED

I have tried several options to get it up an running, but I always get this error message:

```bash
pre-commit run terraform_trivy --all-files
Terraform validate with trivy............................................Failed
- hook id: terraform_trivy
- exit code: 1

2025-03-17T10:34:15.060+0100    ERROR   multiple targets cannot be specified
2025-03-17T10:34:15.060+0100    FATAL   option initialize error: arguments error
```
