### ISSUE TITLE
terraform-docs: Unable to use the 'include' or 'footer-from' options

### ISSUE THREAD

**Issue by rwe-dtroup** [antonbabenko/pre-commit-terraform#874]
I'm unable to find anything to do with this so I'm sure I'm doing something wrong. I'm trying to inject a default set of text with terraform-docs.

If I run terraform docs directly I can pick up the file, but if I run it as part of the pre-commit I get an error

```
Error: stat insert_file.md: no such file or directory
```

I've tried putting the file in a sub folder, and directly in the root of the terraform module. I put the config in the .terraform-docs.yaml file and on the command line in pre-commit but it throws the same error.

```
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.98.1
  hooks:- id: terraform_docs 
      args:
        - '--args=--config=.terraform-docs.yml'
        - '--args=--lockfile=false'
        - '--args=--footer-from=insert_file.md'
```

Is this a bug, or is there a way to fix it?

Any help much appreciated
