### ISSUE TITLE
Terraform fmt fails when fixing a file

### ISSUE THREAD

**Issue by sevenfourk** [antonbabenko/pre-commit-terraform#88]
Hey guys,

running `git commit -va` give me this:

```
Terraform fmt............................................................Failed
- hook id: terraform_fmt
- files were modified by this hook

main.tf

Markdownlint.........................................(no files to check)Skipped
```

```
- repo: git://github.com/antonbabenko/pre-commit-terraform
  rev: v1.24.0 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
  hooks:
    - id: terraform_fmt
- repo: https://github.com/markdownlint/markdownlint
  rev: v0.8.0
  hooks:
    - id: markdownlint
```

we're having terraform dir in a mono-repo for now.

Terraform v0.12.19

Any ideas how to debug that?
