### ISSUE TITLE
terraform_lint doesn't correctly parse args

### ISSUE THREAD

**Issue by grabcocque** [antonbabenko/pre-commit-terraform#93]
I've added the following to my pre-commit config:
```
repos:
  - repo: git://github.com/antonbabenko/pre-commit-terraform
    rev: v1.25.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_tflint
        args: ['--deep']
```

but:

```
$ pre-commit run -a
Terraform fmt............................................................Passed
Terraform validate without variables.....................................Passed
Terraform validate with tflint...........................................Failed
- hook id: terraform_tflint
- exit code: 1

getopt: unrecognized option '--deep'
getopt: unrecognized option '--deep'
getopt: unrecognized option '--deep'
getopt: unrecognized option '--deep'
getopt: unrecognized option '--deep'
getopt: unrecognized option '--deep'
getopt: unrecognized option '--deep'
getopt: unrecognized option '--deep'
```

**Comment by barryib** [comment]
Did you try something like this : 

```yaml
      - id: terraform_tflint
        args: ['args=--deep']
```

**Comment by pietro** [comment]
```yaml
      - id: terraform_tflint
        args: ['args=--deep']
```
works. In order to pass multiple args I had do add `args=` to every arg like:
```yaml
      - id: terraform_tflint
        args:
          - 'args=--deep'
          - 'args=--enable-rule=terraform_documented_variables'
```
