### ISSUE TITLE
Feature: `terraform_validate` to accept arguments

### ISSUE THREAD

**Issue by ctodd-cb** [antonbabenko/pre-commit-terraform#96]
Ideal behavior would mirror `terraform validate --check-variables=false`

I'm trying to use something like this:
```
repos:
- repo: git://github.com/antonbabenko/pre-commit-terraform
  rev: v1.27.0
  hooks:
  - id: terraform_validate
     args: [--args=--check-variables=false]
```
Reponse:
```
Terraform validate without variables.....................................Failed
- hook id: terraform_validate
- exit code: 1

dirname: unrecognized option '--args=--check-variables=false'
Try 'dirname --help' for more information.
```

This is an internal module (no vars supplied) and I can't get past a slew of `Error: Required variable not set: XXYY` errors.
